### ISSUE TITLE
Approval request to publish restructured content

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#106]
@cybersquirrel Hello, please may I request approval to publish updated content? This is for an improved-ease-of-use restructuring, rather than to publish new or modified content.

The most obvious difference is on the landing page (preview [here](https://github.com/ministryofjustice/security-guidance/blob/restruc0901/docs/cyber-and-technical-security-guidance.md)). Previously, many of the topics were 'floating' after the main document list. They have now been integrated more logically into the document list, making it easier to see which content is where.

We have also been able to segregate the content more optimally for the 'tech users' and 'general' audiences. You can see the effect of this most obviously in the offline PDF versions, [here](https://github.com/ministryofjustice/security-guidance/blob/master/docs/moj-guidance-tech.pdf) and [here](https://github.com/ministryofjustice/security-guidance/blob/master/docs/moj-guidance.pdf), respectively.

Thank you.

**Comment by cybersquirrel** [comment]
Hello,

Happy to approve this change.

Longer term I think we might want to rejig the taxonomy as some of these items don't quite slot in right for my expectation around where I'd expect to find them. I don't have any bright ideas for how to fix right now, so I will leave it at this for the time being! 

Thanks,

Jon.

**Comment by warmanaMOJ** [comment]
Thank you.
