### ISSUE TITLE
Request approval to publish update to list of apps

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#107]
@cybersquirrel Please may I request approval to publish an update to the list of approved apps? Specifically, we have added Miro to the list. You can see the preview of addition in the table [here](https://github.com/ministryofjustice/security-guidance/blob/miro0923/docs/general-user-video-and-messaging-apps-guidance.md#approved-tools).

Thank you.

**Comment by cybersquirrel** [comment]
Looks good to me - approved!

**Comment by warmanaMOJ** [comment]
Thank you very much.
