### ISSUE TITLE
Request approval to publish NHS Covid app guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#109]
Please may I request approval to publish guidance regarding installation of the NHS Covid tracking app?

I've added draft material into the general guidance on app usage: the preview is available [here](https://github.com/ministryofjustice/security-guidance/blob/tt1015/docs/general-user-video-and-messaging-apps-guidance.md#nhs-track-and-trace).

Thank you.

**Comment by cybersquirrel** [comment]
This is great - approved. Thank you!

**Comment by warmanaMOJ** [comment]
Thank you - published.
