### ISSUE TITLE
Request approval to publish Technical Security Controls Guide content

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#110]
Hello @cybersquirrel 

Following your reviews of the draft content, we now have a 'camera ready' preview of the Technical Security Guide material as follows:

- [Technical Security Controls Guide](https://github.com/ministryofjustice/security-guidance/blob/techsecconguide1029/docs/technical-security-controls-guide.md)
- [Technical Security Controls Guide: Defensive Layer 1](https://github.com/ministryofjustice/security-guidance/blob/techsecconguide1029/docs/technical-security-controls-guide-defensive-layer-1.md)
- [Technical Security Controls Guide: Defensive Layer 2](https://github.com/ministryofjustice/security-guidance/blob/techsecconguide1029/docs/technical-security-controls-guide-defensive-layer-2.md)

Please may I request approval to publish?

Many thanks,

Adrian

**Comment by cybersquirrel** [comment]
This looks good to me. Approved.

Thank you for your hard work on this.

Jon.

**Comment by warmanaMOJ** [comment]
Thank you. Published.
