### ISSUE TITLE
Request approval to publish new taxonomy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#111]
@cybersquirrel Hello, as discussed, please may I request approval to publish the revised taxonomy for the policy and guidance content? A preview of the revised landing page is [here](https://github.com/ministryofjustice/security-guidance/blob/taxonomy1029/docs/cyber-and-technical-security-guidance.md).

There is no new content in this publication, simply a restructuring of existing material into a taxonomy that better aligns with ISO2700x. We have also included links to existing relevant content published on the Intranet.

Many thanks.

**Comment by cybersquirrel** [comment]
Approved - this looks extremely sensible to me.

Thank you.

**Comment by warmanaMOJ** [comment]
Thank you very much. Published.
