### ISSUE TITLE
Request approval to publish updated passwords guidance, and diagram helping explain Gov007 alignment.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#112]
@cybersquirrel Hello, please may I request approval to publish the updated passwords guidance, and some additional help for understanding the new structure?

All users:

- [Passwords](https://github.com/ministryofjustice/security-guidance/blob/passwords1105/docs/passwords.md)
- [Password managers](https://github.com/ministryofjustice/security-guidance/blob/passwords1105/docs/password-managers.md)

Technical users:

- [Account management](https://github.com/ministryofjustice/security-guidance/blob/passwords1105/docs/account-management.md)
- [Multi-user accounts](https://github.com/ministryofjustice/security-guidance/blob/passwords1105/docs/multi-user-accounts-and-public-facing-service-accounts-guide.md)
- [Password creation and authentication](https://github.com/ministryofjustice/security-guidance/blob/passwords1105/docs/password-creation-and-authentication-guide.md)
- [Password storage and management](https://github.com/ministryofjustice/security-guidance/blob/passwords1105/docs/password-storage-and-management-guide.md)

We've also included a diagram from the Gov007 standard as part of the taxonomy overview, to help with understanding how things fit together, [here](https://github.com/ministryofjustice/security-guidance/blob/passwords1105/docs/cyber-and-technical-security-guidance.md#background).

**Comment by cybersquirrel** [comment]
Another set of excellent work - happy to approve this.

The only niggle I have is that the 'background' section in the front page is getting quite big, and maybe gets in the way of people quickly looking for info. Maybe this is something we could look at with the user research we discussed in the future.

**Comment by warmanaMOJ** [comment]
Thank you - published.

Good point about the background section. The landing page is (currently) oriented towards technical users, so it indeed has a lot more detail such as the diagram. However, when you look at the '[all users version](https://ministryofjustice.github.io/security-guidance/moj-guidance.pdf)', the background section is almost non-existent, because it's simply not needed.

Anyway, I'll work on changing the GitHub landing page to simplify things.

Thanks again.
