### ISSUE TITLE
[REQUEST] Add search bar to site

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/security-guidance#113]
## Team

P&A, LAA Ops

## User needs

As a ops engineer

When I want to find security guidance I would like to use a search bar

Because I want to find information quickly

## Detailed request description

Please could you add a search bar to the site to make finding things easier!  Cheers!

**Comment by warmanaMOJ** [comment]
Hi, thanks for your request.

We are very aware that an in-built search facility would be helpful, however, I'm afraid that for a variety of reasons it's not something that is currently at the top of our To Do list. But it _is_ on our To Do list.

In the meantime, I've added some content [here](https://ministryofjustice.github.io/security-guidance/#searching-this-content) which provides some tips on how to find information. I know it's not the same as a search bar, but hopefully will make the wait a little less painful.

Thanks again!
