### ISSUE TITLE
Request approval to publish vulnerability and patch management guidance updates

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#119]
Hello @cybersquirrel ,

Please may I request approval to publish the updated Vulnerability Scanning and Patch Management guidance? The final drafts can be previewed as follows:

- [Vulnerability Scanning and Patch Management Guide](https://github.com/ministryofjustice/security-guidance/blob/patch0126/docs/vulnerability-scanning-and-patch-management-guide.md) - the 'parent' topic.
- [Vulnerability Scanning Guide](https://github.com/ministryofjustice/security-guidance/blob/patch0126/docs/vulnerability-scanning-guide.md)
- [Patch Management Guide](https://github.com/ministryofjustice/security-guidance/blob/patch0126/docs/patch-management-guide.md)

Please note that the Patch Management Guide draft has been reviewed to ensure that it incorporates the key points from the existing guidance published on the Intranet [here](https://intranet.justice.gov.uk/guidance/security/it-computer-security/ict-security-policy-framework/patch-management-standard/). The intention is that the older Intranet content will be removed ASAP, having been replaced by this newer Patch Management Guide.

Many thanks,

Adrian

**Comment by cybersquirrel** [comment]
Approved. Thank you all for your hard work on this.

**Comment by warmanaMOJ** [comment]
Thank you very much, published.
