### ISSUE TITLE
Please define external collaborators in code

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/security-guidance#120]
Hi there

We now have a process to manage github collaborators in code:
https://github.com/ministryofjustice/github-collaborators/blob/main/README.md#github-external-collaborators

Please follow the procedure described there to grant @tomdMOJ access to this repository.

If you have any questions, please post in #ask-operations-engineering on Slack.

**Comment by tomdMOJ** [comment]
Hi, 

Adrian Warman (@warmanaMOJ) responded to this yesterday. Can you let me know what else needs to be done. I've had full access to GitHub for a number of years.

**Comment by AntonyBishop** [comment]
Hi @tomdMOJ. Not how Adrian has responded to this. 

The process in https://github.com/ministryofjustice/github-collaborators/blob/main/README.md#github-external-collaborators needs to be followed for code contributors who are now part if the MoJ Organisation.

Any questions please let me know.

**Comment by tomdMOJ** [comment]
Adrian tells me that the matter has been resolved with merge for collaborators having taken place. Is there a waiting period before it filters down to me as I still don't have access to push to security-guidance. I did have access 3 days ago.

**Comment by AntonyBishop** [comment]
Hi @tomdMOJ you have been added. It's possible that you need to be invited by the owner of this repository?

**Comment by AntonyBishop** [comment]
As I'm an admin I have added you. Adding you in TF should mean that you don't get bounced off overnight. Should be able to do the necessary now.
