### ISSUE TITLE
Request approval to publish updates to Enterprise Access Control policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#122]
@cybersquirrel 

Hello, the JML project team have identified some interim updates to the EAC policy, to clarify links to published joiner and leaver processes, and to clarify account removal details.

You can see drafts of changes in preview form here (in the Note immediately before [this heading](https://github.com/ministryofjustice/security-guidance/blob/enterpriseaccess0208/docs/enterprise-access-control-policy.md#user-registration-and-account-creation) ), and [here](https://github.com/ministryofjustice/security-guidance/blob/enterpriseaccess0208/docs/enterprise-access-control-policy.md#account-removal), respectively.

Please may I request approval to publish these updates?

Thank you.

**Comment by cybersquirrel** [comment]
Wow, the rest of that doc is in sore need of an update (references to IL3, and REST*, date it a lot). But these tweaks are fine.

**Comment by warmanaMOJ** [comment]
Thank you, published. (And yes, we have a backlog task to address the wider updating requirement!)
