### ISSUE TITLE
Request approval to publish updates to Accessing MoJ IT from overseas

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#123]
@cybersquirrel 

Hello, following feedback and update requests from OST, we have updated the list of high attention countries, the section on what to do if you have any problem when using MoJ equipment overseas, and the contact details for reporting an incident.

You can see previews of the draft updates [here](https://github.com/ministryofjustice/security-guidance/blob/accessAbroad0211/docs/accessing-moj-it-systems-from-overseas.md#part-one), [here](https://github.com/ministryofjustice/security-guidance/blob/accessAbroad0211/docs/accessing-moj-it-systems-from-overseas.md#if-you-have-any-problem-when-using-moj-equipment-overseas), and [here](https://github.com/ministryofjustice/security-guidance/blob/accessAbroad0211/docs/accessing-moj-it-systems-from-overseas.md#information-incident-reporting-line), respectively.

Please may I request approval to publish these updates?

Many thanks.

**Comment by cybersquirrel** [comment]
Approved - thank you.

**Comment by warmanaMOJ** [comment]
Thank you, published.
