### ISSUE TITLE
Request approval to publish update to domain registration

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#124]
@cybersquirrel 

Hello, in response to a question and feedback, we've updated the guidance on defensive domain registration to include a section about Decommissioning a domain, and providing guidance on how to keep a domain for.

You can see a preview of the draft update [here](https://github.com/ministryofjustice/security-guidance/blob/decomDomain0208/docs/defensive-domain-registration.md#decommissioning-a-domain).

Please may I request approval to publish?

Many thanks.

**Comment by cybersquirrel** [comment]
Looks good to me - approved!

**Comment by warmanaMOJ** [comment]
Thank you, published.
