### ISSUE TITLE
Request approval to publish updated BYOD guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#125]
Hello @cybersquirrel 

Many thanks for the feedback; I have updated the draft accordingly (preview [here](https://github.com/ministryofjustice/security-guidance/blob/byod0215/docs/personal-devices.md) ).

Please may I request approval to publish this updated content?

Thank you.

**Comment by cybersquirrel** [comment]
Looks super - thank you. Approved.

**Comment by warmanaMOJ** [comment]
Thank you, published.
