### ISSUE TITLE
Request approval to publish updated guidance on logging and log retention.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#126]
Hello @cybersquirrel 

Following the discussion recently, the guidance on logging and log retention has been restructured into two, more logical files [here](https://github.com/ministryofjustice/security-guidance/blob/logging0218/docs/logging-and-monitoring.md) and [here](https://github.com/ministryofjustice/security-guidance/blob/logging0218/docs/online-identifiers.md).

In addition to the restructuring, there is added detail on retention times, [here](https://github.com/ministryofjustice/security-guidance/blob/logging0218/docs/logging-and-monitoring.md#log-retention).

Please may I request approval to publish?

Many thanks.

**Comment by cybersquirrel** [comment]
This is great - thank you, approved.

**Comment by warmanaMOJ** [comment]
Thank you very much, published.
