### ISSUE TITLE
Request Approval to publish Physical Security Policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#128]
Hello @cybersquirrel 

Please may I request approval to publish the updated Physical Security Policy? The draft preview is visible [here](https://github.com/ministryofjustice/security-guidance/blob/physical0223/docs/physical-security-policy.md).

The content has been created in conjunction with, and has been reviewed and accepted by, Simon E. in Group Security.

Thanks and regards,

Adrian

**Comment by cybersquirrel** [comment]
Approved - thank you.

**Comment by warmanaMOJ** [comment]
Thank you very much. Published.
