### ISSUE TITLE
Request approval to publish fixes for broken URLs, and contact details added to Policy document.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#129]
Hello @cybersquirrel 

Please may I request approval to publish some modest updates:

1. Corrections on the General Apps content [preview here](https://github.com/ministryofjustice/security-guidance/blob/fixurls0303/docs/general-user-video-and-messaging-apps-guidance.md#storage-and-data-retention), where links to Intranet content are broken following some restructuring.
2. Addition on contact details for Group Security [preview here](https://github.com/ministryofjustice/security-guidance/blob/fixurls0303/docs/physical-security-policy.md#physical-security-advice), for those wanting further assistance.

Many thanks.

**Comment by cybersquirrel** [comment]
Approved - thank you.

**Comment by warmanaMOJ** [comment]
Thank you very much - published.
