### ISSUE TITLE
Request approval to publish guidance on re-classifying information

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#133]
Hello @cybersquirrel 

Please may I request approval to publish some updated policy and guidance, regarding re-classifying information?

A preview of the new material can be seen in the policy [here](https://github.com/ministryofjustice/security-guidance/blob/reclassify0301/docs/information-classification-and-handling-policy.md#reclassifying-information) and the guidance [here](https://github.com/ministryofjustice/security-guidance/blob/reclassify0301/docs/information-classification-handling-and-security-guide.md#reclassification-examples). The latter reference also includes some illustrative scenarios.

Many thanks!

**Comment by cybersquirrel** [comment]
This is approved - thank you.

**Comment by warmanaMOJ** [comment]
Thank you. Published.
