### ISSUE TITLE
Request approval to publish guidance on IT Accounts and Assets for Long Term Leave

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#134]
Hello @cybersquirrel 

Please may I request approval to publish a copy of the JML guidance on IT Accounts and Assets for Long Term Leave? This is content that is already approved and live on the Intranet, and is being brought into the IT Security policy content set to facilitate on-going support and maintenance.

You can see a preview of the content [here](https://github.com/ministryofjustice/security-guidance/blob/ltasset0330/docs/long-term-leave.md). A link to the published version on the Intranet was supplied previously in an email from the JML project.

Many thanks.

**Comment by cybersquirrel** [comment]
Approved. Thank you!

**Comment by warmanaMOJ** [comment]
Thank you, published.
