### ISSUE TITLE
Request Approval to Publish additional material for Baseline AWS guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#141]
Hello @cybersquirrel 

Please may I request approval to publish some additional material into the Baseline AWS guidance, specifically a paragraph on IAM Access Analyzer? The material was supplied by @jakemulley in the Hosting and DigOps team.

A preview of the additional section can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/iamaa0407/docs/baseline-aws-accounts.md#iam-access-analyzer).

Many thanks.

**Comment by cybersquirrel** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you. Published.
