### ISSUE TITLE
Request Approval to Publish Legacy content

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#142]
Hello @cybersquirrel 

Further to our recent email exchange, please may I request approval to publish the following four migrated content files:
[Source Code Publishing](https://github.com/ministryofjustice/security-guidance/blob/migrate0401/docs/source-code-publishing.md)
[System Test Standard](https://github.com/ministryofjustice/security-guidance/blob/migrate0401/docs/system-test-standard.md)
[Forensic Principles](https://github.com/ministryofjustice/security-guidance/blob/migrate0401/docs/forensic-principles.md)
[Forensic Readiness Guide](https://github.com/ministryofjustice/security-guidance/blob/migrate0401/docs/forensic-readiness-guide.md)

As noted, some of these do require significant updating; this task has been captured in our Backlog for processing ASAP.

Many thanks.

**Comment by cybersquirrel** [comment]
Happy to approve with the caveat as noted!

Jon.

**Comment by warmanaMOJ** [comment]
Thank you, published.
