### ISSUE TITLE
Request for additional sign-off approver

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#143]
Hello @cybersquirrel 

As discussed, please may I request approval for signing off the publication of security guidance updates, as follows:

**Policy content (normally identified as "'XYZ' Policy")**
Jon only

**Non-policy content (processes, guides or guidance, standards, FAQs)**
Jon or Luke - either approving is sufficient.

Thank you.

**Comment by cybersquirrel** [comment]
I am happy to approve this new approach as described, with @L-Crosby taking on additional responsibilities for the content approvals, recorded in this fashion through GitHub issues.

Thank you!

**Comment by warmanaMOJ** [comment]
Thank you. This will take effect immediately.

**Comment by L-Crosby** [comment]
Thank you both.
