### ISSUE TITLE
Request Approval to publish Access Control Policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#144]
Hello @cybersquirrel 

Please may I request approval to publish the Access Control Policy. A preview of the content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/acp0416/docs/access-control-policy.md).

(Copy @L-Crosby , FYI.)

Thank you.

**Comment by cybersquirrel** [comment]
Delighted to do so - another excellent update to the policy portfolio, thank you team!

**Comment by warmanaMOJ** [comment]
Thank you. Published.
