### ISSUE TITLE
Request to note updates

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#145]
Hello @L-Crosby ,

To better align the GitHub and Intranet content, some stylistic changes have been made to the information.

These include:

- Removed quote marks from emphasis on Intranet version, for style compliance.
- Moved some sections from sub-sub-heading to sub-heading, for style compliance.
- Added 'contact details' section if it was not present.
- Removed 'Note' indicator in some cases, for style compliance.
- Removed questions in titles, for style compliance.

As specific examples:

- [official, official-sensitive GitHub version](https://github.com/ministryofjustice/security-guidance/blob/intranetRefresh0429/docs/official-official-sensitive.md) [official, official-sensitive Intranet version](https://github.com/ministryofjustice/security-guidance/blob/intranetRefresh0429/intranet/official-official-sensitive.md) - added emphasis markup for classification and handling caveats.
- [Secure disposal of IT equipment Github version](https://github.com/ministryofjustice/security-guidance/blob/intranetRefresh0429/docs/secure-disposal-of-it-equipment.md) [Secure disposal of IT equipment Intranet version](https://github.com/ministryofjustice/security-guidance/blob/intranetRefresh0429/intranet/secure-disposal-of-it-equipment.md) - heading capitalisations adjusted for style compliance, also heading clarification for section listing approved organisations.

To be clear, **no** security policy, standard or guidance information has changed. *Only* modifications to style.

As such, I'm not request approval to publish for these changes, but I would appreciate you 'noting' this Issue.

Naturally, if you prefer more detail, or a formal request for approval to publish, that would be fine.

Thank you.

**Comment by L-Crosby** [comment]
Noted. All seems to make sense to me. No issues here.

**Comment by warmanaMOJ** [comment]
Thank you very much, updates published.
