### ISSUE TITLE
Request approval to publish mobile device and remote working policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#147]
Hello @cybersquirrel 

Please may I request approval to publish the updated Mobile Device and Remote Working policy?

A preview of the content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/policy0322/docs/mobile-device-and-remote-working-policy.md).

Many thanks.

**Comment by cybersquirrel** [comment]
Hello - thanks for this - it is generally very clear and well put together. Specific comments:

POLMOB003 - I get intent, but in practice this would mean we couldn't have a self-service app store with approved enterprise apps. I think we mean 'unconstrained' or 'unapproved' installation?

POLMOB005 - similar to 003, I think this is phrased strangely, and would (ironically for me) be better phrased as a "do not" type policy control - or at least "it must be possible to monitor and constrain the apps and services that are accessed from the device"?

POLMOB007 - slightly unsure what is an acceptable level of protection here. Probably this is ok at this level of the policy stack, but the detail is hard - is leaving a laptop unseen in the locked boot of a car in an MoJ carpark ok / not ok? 

POLMOB009 - unclear on difference between this and 007?

POLMOB010 - except...BYOD...maybe "personal devices can only be used for work purposes in accordance with our BYOD policy"?

The 'remote working' section doesn't seem to fit with how we actually do remote working these days? A few of these really shouldn't matter given the other policies we have around the way our remote working devices operate (e.g. malware protection, firewalls etc). 


Best wishes,

Jon.

**Comment by warmanaMOJ** [comment]
Hello @cybersquirrel (cc @L-Crosby )

(With apologies for the delay...) I have made changes to the content as per your feedback. The updated draft can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/policy0322/docs/mobile-device-and-remote-working-policy.md).

Please may I request approval to publish?

Many thanks.

**Comment by cybersquirrel** [comment]
The changes here look absolutely on the mark in addressing the comments I made previously. Happy to approve this for publication.

Thanks to all who have worked hard on this.

Jon.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://ministryofjustice.github.io/security-guidance/mobile-device-and-remote-working-policy/#mobile-device-and-remote-working-policy).
