### ISSUE TITLE
Request approval to remove older, redundant content.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#149]
Hello @L-Crosby 

Please may I request approval to remove the older content on Personnel Security Clearances ([here](https://ministryofjustice.github.io/security-guidance/personnel-security-clearances/#personnel-security-clearances) ).

It is redundant in view of the more detailed information already published on Minimum User Clearance Requirements ([here](https://ministryofjustice.github.io/security-guidance/minimum-user-clearance-requirements-guide/#minimum-user-clearance-requirements-guide) ).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. Happy with this. I do think we need a bit more guidance on security clearance for developers and other technical staff (do they need SC clearance) as at the moment we seem to be giving inconsistent messages across the team.
