### ISSUE TITLE
Request approval to publish update to Social Media app guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#152]
Hello @L-Crosby 

Please may I request approval to publish an update to the Social Media app guidance?

A preview of the content is available [here](https://github.com/ministryofjustice/security-guidance/blob/whatsapp0520/docs/protecting-social-media-accounts.md#check-your-privacy-settings). The new material includes a link to WhatsApp privacy settings, and also provides a specific example of preventing any third party from adding your WhatsApp account to one of their groups without your knowledge.

For comparison, the currently published material is [here](https://ministryofjustice.github.io/security-guidance/protecting-social-media-accounts/#check-your-privacy-settings).

Many thanks.

**Comment by L-Crosby** [comment]
17 mins is a bit more like it. Approved. I like the general tone and clarity of this. Can you let me know when you have published this so I can send it to James McEwen as he was asking questions about this.

**Comment by warmanaMOJ** [comment]
Thank you. Published ([here](https://ministryofjustice.github.io/security-guidance/protecting-social-media-accounts/#check-your-privacy-settings)).
