### ISSUE TITLE
Request Approval to Publish updated travel guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#153]
Hello @L-Crosby ,

Please may I request approval to publish updated travel guidance, based on feedback from Operational Security Team?

The preview of the updated content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/overseas0521/docs/accessing-moj-it-systems-from-overseas.md).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. Happy for this to be published. 
In slower time, the one thing that occurred to me is the link to BOYD. Do we need to remind people that if there are MoJ services that they can access from personal device they should not be doing so (especially abroad). I am worried about people using WhatsApp, slack, g-suite etc on personal mobiles. Happy to discuss this one in more detail.

**Comment by warmanaMOJ** [comment]
Thank you. Published.

I've added your additional note into our Trello backlog.
