### ISSUE TITLE
Request Approval to Publish updated Overseas Travel guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#154]
Hello @L-Crosby ,

Please may I request approval to publish updated Overseas Travel guidance? You can see a preview of the content [here](https://github.com/ministryofjustice/security-guidance/blob/overseastravel0519/intranet/overseas-travel.md).

This material is for Group Security, and sits outside the IT Security area on the Intranet. You can see the current content on the Intranet [here](https://intranet.justice.gov.uk/guidance/security/travelling-abroad-business-or-personal/).

For reference, the complete set of changes in this request can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...overseastravel0519). Note that some of the more detailed changes (other than the `overseas-travel.dita` file) are bug fixes to improve the build process.

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, published.
