### ISSUE TITLE
Request approval to publish additional guidance for acceptable use.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#155]
Hello @L-Crosby ,

Please may I request approval to publish an update to the Acceptable Use Guidance, specifically to require people to report lost, stolen, or wilfully damage to MoJ equipment to the Police and Service desk. A preview of the new paragraph can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/aupWilful0526/docs/acceptable-use.md#keeping-control).

This change was requested by OST, and the preview has been checked by them.

Many thanks.

**Comment by L-Crosby** [comment]
Looks good to me. Seems to fit well with the rest of the document. Approved.

**Comment by warmanaMOJ** [comment]
Thank you. Published.
