### ISSUE TITLE
Request Approval to Publish Intranet content update

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#156]
Hello @L-Crosby ,

Please may I request approval to publish updates in preparation for the June 2021 Intranet content refresh drop?

The full set of changes can be previewed in [this view](https://github.com/ministryofjustice/security-guidance/compare/main...intranet0527).

**Note:** It looks like a huge number of changes, but in fact there are no significant content changes in this request; *all* of the modifications are to better align the generated markdown with the Intranet requirements.

We have also supplied two 'landing pages' ([Equipment](https://github.com/ministryofjustice/security-guidance/blob/intranet0527/intranet/equipment.md) and [Equipment management](https://github.com/ministryofjustice/security-guidance/blob/intranet0527/intranet/equipment-management.md) respectively) - these were requested by the Intranet team as pages under which to structure existing pages, and are effectively null content. They do not appear within the GitHub content.

Many thanks.

**Comment by L-Crosby** [comment]
All makes sense to me. Approved.

**Comment by warmanaMOJ** [comment]
Thank you very much. Published.
