### ISSUE TITLE
Request Approval to Publish clarification note.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#157]
Hello @L-Crosby ,

Please may I request approval to publish an additional note in the Acceptable Use guidance, [here](https://github.com/ministryofjustice/security-guidance/blob/aup0528/docs/acceptable-use.md#keeping-control)?

The `Note` has been added, based on some feedback that indicated some readers might think a report must always be made, whereas there might be circumstances where a more sensitive handling is appropriate.

In the original guidance, we are correctly using the phrase "should", which denotes a recommendation or advisory stance, rather than "shall" which is a required or mandatory stance.

Nevertheless, the subtleties of the terminology might cause problems, so adding this note of clarification is entirely consistent with the original guidance but hopefully reduces any uncertainty.

Many thanks.

**Comment by L-Crosby** [comment]
Approved. I have seen the discussions associated with this update. Seems like a pragmatic approach.

**Comment by warmanaMOJ** [comment]
Thank you. Published.
