### ISSUE TITLE
Request Approval to Publish updated Security Vetting materials.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#158]
Hello @L-Crosby ,

Please may I request approval to publish updated Security Vetting materials, namely:

- [End or change of employment](https://github.com/ministryofjustice/security-guidance/blob/nsv0521/docs/end-or-change-of-employment.md)
    - [The associated document in word format](https://github.com/ministryofjustice/security-guidance/blob/nsv0521/docs/gs/end-or-change-of-employment.docx)
- [National Security Vetting questions](https://github.com/ministryofjustice/security-guidance/blob/nsv0521/docs/national-security-vetting-questions.md)
    - [The associated document in word format](https://github.com/ministryofjustice/security-guidance/blob/nsv0521/docs/gs/national-security-vetting-questions.docx)
- [The security Vetting Assessment Need doc - download only, not a webpage](https://github.com/ministryofjustice/security-guidance/blob/nsv0521/docs/gs/security-vetting-assessment-need.doc).

(The final document is a complex form, and would not benefit from conversion to a web page.)

These changes have all been requested and reviewed by OST.

Many thanks.

**Comment by L-Crosby** [comment]
Approved. We have discussed some content needed for SC clearance for certain roles (especially developers) but this is expected in a later revision.

**Comment by warmanaMOJ** [comment]
Thank you. Published.
