### ISSUE TITLE
Request Approval to Publish revised list of 'attention' countries for overseas travel.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#159]
Hello @L-Crosby ,

Please may I request approval to publish an updated list of countries to consider when planning overseas travel. The preview of the change is [here](https://github.com/ministryofjustice/security-guidance/blob/overseas0528/docs/accessing-moj-it-systems-from-overseas.md#part-one).

Specifically, Northern Cyprus is [not recognised by the British Government](https://www.gov.uk/foreign-travel-advice/cyprus/safety-and-security), so the phrasing has been changed for Cyprus.

Many thanks.

**Comment by L-Crosby** [comment]
I saw the discussion with Jake on this. Good to respond to user feedback. Approved.

**Comment by warmanaMOJ** [comment]
Thank you. Published.
