### ISSUE TITLE
Request Approval to Publish clarification about app-based password best practices

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#160]
Hello @L-Crosby 

Please may I request approval to publish clarification about (not) using application-based passwords to protect information.

The new material can be seen as a preview section, [here](https://github.com/ministryofjustice/security-guidance/blob/excel0609/docs/passwords.md#app-based-password-protection-for-files).

Many thanks.

**Comment by L-Crosby** [comment]
Very clear! Approved.

**Comment by warmanaMOJ** [comment]
Thank you. Content published.
