### ISSUE TITLE
Request Approval to Publish guidance about (not) using AutoFill to store passwords or credit card details.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#161]
Hello @L-Crosby 

Please may I request approval to publish additional guidance about not using app-based AutoFill mechanisms to store sensitive material, such as credit card details.

The additional material can be seen in preview form, and consists of:

- [Bullet added, making clear that using unapproved tools to store credit card details is not acceptable use of MoJ IT](https://github.com/ministryofjustice/security-guidance/blob/autofill0603/docs/acceptable-use.md#unacceptable-use-of-moj-it)
- [Paragraph added advising not to use unapproved Autofill tools](https://github.com/ministryofjustice/security-guidance/blob/autofill0603/docs/password-storage-and-management-guide.md#password-storage)

Many thanks.

**Comment by L-Crosby** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you. Content published.
