### ISSUE TITLE
Request Approval to Publish guidance on Data Movement Forms

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#162]
Hello @L-Crosby 

Please may I request approval to publish clarification guidance on scenarios where Data Movement Forms are required, and for what purpose?

This follows a clarification request from a project team. The clarification material has been reviewed and agreed with the Operational Security Team.

The new clarification can be seen as a preview, [here](https://github.com/ministryofjustice/security-guidance/blob/dmf0525/docs/data-handling-and-information-sharing-guide.md#data-movement-form-dmf).

The complete set of changes (which includes stylistic improvements and restructuring for clarity), can be seen using the comparison tool [here](https://github.com/ministryofjustice/security-guidance/compare/main...dmf0525).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you. Published.
