### ISSUE TITLE
Request approval to publish content revised for Intranet compliance.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#163]
Hello @L-Crosby,

Please may I request approval to publish some changes to the Intranet version of content, primarily affecting the "Accessing MoJ IT systems overseas" content.

The changes are minor, overall, but reflect Intranet requirements. There is also a style guide compliance change; [GDS advice](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style) is that we should use the term `wifi` rather than `WiFi`.

The preview of the Intranet version of the 'Accessing...' document can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/access0614/intranet/accessing-moj-it-systems-from-overseas.md).

A full set of all the changes can be seen in [this comparison](https://github.com/ministryofjustice/security-guidance/compare/main...access0614).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you. Published.
