### ISSUE TITLE
Request Approval to Publish guidance on Secure Data/File transfers

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#164]
Hello @L-Crosby 

Please may I request approval to publish the following (significant) guidance on secure information transfer,
available for preview:

- [Secure Data Transfer Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/secure-data-transfer-guide.md)
- [Secure Email Transfer Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/secure-email-transfer-guide.md)
- [Email Security Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/email-security-guide.md)
- [Email Authentication Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/email-authentication-guide.md)
- [Spam and Phishing Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/spam-and-phishing-guide.md)

The complete set of changes when compared with existing published material is visible [here](https://github.com/ministryofjustice/security-guidance/compare/main...transfer0607).

Many thanks.

**Comment by L-Crosby** [comment]
In the transfer considerations section of the Secure Data Transfer Guide - These **conisderations** apply when transmitting any data - the word considerations is misspelt.

**Comment by L-Crosby** [comment]
In Secure Data Transfer Guide - is there any guidance on what people should do if they do not know who the data controller is?

**Comment by L-Crosby** [comment]
In the Secure Data Transfer Guide - in terms of CJSM email, we use **eMail** with a capital M in one place and not elsewhere. I suggest we just use email as the conventional spelling

**Comment by L-Crosby** [comment]
In Secure Email Transfer Guide - where we talk about Gmail and O365 should we distinguish explicitly between corporate and personal email?

**Comment by L-Crosby** [comment]
In the email security guide - where we say 'Deprecate the downloading of data to mobile devices'. Would this be better in plainer English?

**Comment by L-Crosby** [comment]
In the email security guide - **Ensure suspected or actual phishing emails are easily communicated to the Technology Service Desk as email attachments** - I think we need to be clearer about what we want users to do here. Consider rewording?

**Comment by L-Crosby** [comment]
On Delegate access in the email security guide - Would it be worth linking to JML processes?

**Comment by L-Crosby** [comment]
Approved - Can the typographical changes and rewording suggestion be made before publication. All other changes can be made a later date if necessary.

**Comment by warmanaMOJ** [comment]
Thank you - we'll fix those things and re-submit the RAP. There's enough there that I'd like it to be right (or at least better) before publishing.

**Comment by warmanaMOJ** [comment]
Hello @L-Crosby 

Please may I request approval to publish the following (significant) guidance on secure information transfer,
available for preview, and updated following feedback:

- [Secure Data Transfer Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/secure-data-transfer-guide.md)
- [Secure Email Transfer Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/secure-email-transfer-guide.md)
- [Email Security Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/email-security-guide.md)
- [Email Authentication Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/email-authentication-guide.md)
- [Spam and Phishing Guide](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/spam-and-phishing-guide.md)

There is also a significant expansion of general guidance regarding email, for all MoJ colleagues, [here](https://github.com/ministryofjustice/security-guidance/blob/transfer0607/docs/email.md).

Lastly, there are some minor stylistic, spelling and grammar corrections across various files.

The complete set of changes when compared with existing published material is visible [here](https://github.com/ministryofjustice/security-guidance/compare/main...transfer0607).

Many thanks.

**Comment by L-Crosby** [comment]
Going through them in turn. 
Secure data transfer guide - Approved
Secure email transfer guide - Approved
(Appreciate seeing my earlier comments reflected in changes)

**Comment by L-Crosby** [comment]
On the general user email guidance - Happy to approve but there is an awful lot to take in here. I really like the explanations and background but I wonder if there need to be some top tips, key messages type guidance that goes along with this. There might also be a need for more visual messages in this as it is such a hot and current topic.

**Comment by L-Crosby** [comment]
Thanks to everyone for their efforts on this. (Don't know if thanks belong in a formal approval record but I think its important)

**Comment by warmanaMOJ** [comment]
Thank you, published.
