### ISSUE TITLE
Request Approval to Publish guidance on equipment reassignment.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#165]
Hello @L-Crosby ,

Please may I request approval to publish new guidance on equipment reassignment?

You can see a preview of the new content, [here](https://github.com/ministryofjustice/security-guidance/blob/reassign0616/docs/equipment-reassignment-guide.md).

Many thanks.

**Comment by L-Crosby** [comment]
Approved - it would be good if we made a link to JML and reference to the leavers checklist in the guidance but that is not a barrier to publishing.

**Comment by warmanaMOJ** [comment]
Thank you. Published.
