### ISSUE TITLE
Request Approval to Publish Pre-Employment Screening and Vetting of External Candidates - FAQs

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#166]
Hello @L-Crosby 

Please may I request approval to publish the Group Security guidance: Pre-Employment Screening and Vetting of External Candidates - FAQs.

A preview of the content (which has been supplied and reviewed by Group Security) is [here](https://github.com/ministryofjustice/security-guidance/blob/screen0617/docs/pre-employment-screening-and-vetting-of-external-candidates-faqs.md).

Thank you.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you. Published.
