### ISSUE TITLE
Request Approval to Publish fixes for broken Intranet links

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#168]
Hello @L-Crosby 

Previously, we have linked to Intranet content from the published GitHub material. Many of the links were broken. While the Intranet content is being reviewed, I've removed the links from the GitHub material.

This RAP is simply to remove Intranet links temporarily. A full set of the changes in this RAP is [here](https://github.com/ministryofjustice/security-guidance/compare/main...intranetLinks0628).

Thank you.

**Comment by L-Crosby** [comment]
Makes sense. Approved.

**Comment by warmanaMOJ** [comment]
Thank you, published.
