### ISSUE TITLE
Request Approval to Publish updates: avoiding print redirection.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#169]
Hello @L-Crosby 

Following conversations with a Lead Cyber Security Risk Advisor, I've updated material in Remote Working and Acceptable Use, clarifying that people should not redirect print jobs from MoJ printers to personal printers.

You can see previews of the new material (as specific bullets), [here](https://github.com/ministryofjustice/security-guidance/blob/printRedirect0628/docs/remote-working.md#protecting-your-workspace-and-equipment), [here](https://github.com/ministryofjustice/security-guidance/blob/printRedirect0628/docs/remote-working.md#using-your-own-equipment), and [here](https://github.com/ministryofjustice/security-guidance/blob/printRedirect0628/docs/acceptable-use.md#unacceptable-use-of-moj-it).

I've checked these changes with the SME, and had confirmation that they meet the requirements.

The full set of changes can be previewed [here](https://github.com/ministryofjustice/security-guidance/compare/main...printRedirect0628).

Please may I request approval to publish this new material?

Many thanks.

**Comment by L-Crosby** [comment]
Approved. Very sensible and clear and lovely to see the feedback loop working so speedily.

**Comment by warmanaMOJ** [comment]
Thank you, published.
