### ISSUE TITLE
Request Approval to Publish clarification about avoiding use of app-based password tooling.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#170]
Hello @L-Crosby 

Please may I request approval to publish some clarification about tools that include support password encryption of files?

You can see a preview of the clarified paragraph [here](https://github.com/ministryofjustice/security-guidance/blob/passwordApps0628/docs/passwords.md#app-based-password-protection-for-files).

A complete preview of all the changes is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...passwordApps0628).

Many thanks.

**Comment by L-Crosby** [comment]
We discussed this on the standup so I understand this one fully and am pleased to see we are responding to user feedback. Approved.

**Comment by warmanaMOJ** [comment]
Thank you, published.
