### ISSUE TITLE
Request Approval to Publish updated guidance on Supplier use of their corporate IT.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#172]
Hello @L-Crosby 

Following some great feedback, some updates have been made to the guidance on Supplier use of their corporate IT. You can see the preview [here](https://github.com/ministryofjustice/security-guidance/blob/supplier0618/docs/supplier-corporate-it.md).

The emphasis of the changes is to highlight the importance of stronger controls and processes for MoJ material with handling caveats, such as `OFFICIAL-SENSITIVE`.

A full set of the changes introduced in this update is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...supplier0618).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. One comment where we say _'Supplier staff are not prohibited from working overseas while processing OFFICIAL MoJ data, subject to implementing and maintaining acceptable information controls and governance' - is there a reason why do not just link to our security guidance and hold them to a similar standard to us?

**Comment by warmanaMOJ** [comment]
Thank you @L-Crosby , good point.

I've added a clarifying sentence [here](https://github.com/ministryofjustice/security-guidance/blob/supplier0618/docs/supplier-corporate-it.md#working-overseas). Is that OK?

**Comment by L-Crosby** [comment]
Looks good to me.

**Comment by warmanaMOJ** [comment]
Thank you, published.
