### ISSUE TITLE
Request Approval to Publish updated guidance on Data Movement Forms.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#173]
Hello @L-Crosby 

Following a continuation of the conversation about Data Movement Forms (DMFs), and also the release of an updated copy of the actual form, so modest changes have been made to the content [here](https://github.com/ministryofjustice/security-guidance/blob/dmf0615/docs/data-handling-and-information-sharing-guide.md#data-movement-form-dmf).

The main changes are to support an update to the download document, and clarifications about data bearing assets and scenarios where DMFs are required.

A full set of the changes can be viewed [here]().

Please may I request approval to publish?

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, published.
