### ISSUE TITLE
Request Approval to Publish guidance for Leavers with NSV

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#174]
Hello @L-Crosby 

Please may I request approval to publish updated guidance for people leaving the Ministry of Justice (MoJ), who have National Security Vetting (NSV), or who are National Security Vetting Contacts (NSVCs)?

This material was supplied by Group Security, and has been checked by them.

A preview of the content may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/leavers0701/docs/leavers-with-nsc-and-nscvs.md).

The complete set of changes may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...leavers0701).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, published.
