### ISSUE TITLE
Request Approval to Publish guidance for Pre-employment screening

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#175]
Hello @L-Crosby 

Please may I request approval to publish updated guidance for Pre-employment screening?

This material was supplied by Group Security, and has been checked by them.

A preview of the content may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/screen0623/docs/pre-employment-screening.md).

The complete set of changes may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...screen0623).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, published.
