### ISSUE TITLE
Request Approval to Publish NSV for External Candidates FAQ

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#176]
Hello @L-Crosby 

Please may I request approval to publish these FAQs regarding NSV for external candidates?

This material was supplied by Group Security, and has been checked by them.

A preview of the content may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/external0701/docs/national-security-vetting-for-external-candidates-faq.md).

The complete set of changes may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...external0701).

Many thanks.

**Comment by warmanaMOJ** [comment]
Thank you, published. I've requested addition of 'SCSBP' and Oleeo' to the MoJ Acronym list, [here](https://ministryofjustice.github.io/acronyms/).

**Comment by warmanaMOJ** [comment]
@L-Crosby : The two additions are now in the Acronym list.

**Comment by L-Crosby** [comment]
Thanks!
