### ISSUE TITLE
Request Approval to Publish information on the security clearance appeals policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#177]
Hello @L-Crosby

Please may I request approval to publish information on the security clearance appeals policy?

This material was supplied by Group Security, and has been checked by them.

A preview of the content may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/appeals0702/docs/security-clearance-appeals-policy.md).

The complete set of changes may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...appeals0702).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, published.
