### ISSUE TITLE
Request Approval to Publish Voluntary Drug Testing material

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#178]
Hello @L-Crosby 

Please may I request approval to publish two documents. They have both been supplied and reviewed by Group Security.

The two documents are available as previews:

- [Voluntary drug testing policy](https://github.com/ministryofjustice/security-guidance/blob/voluntaryPolicy0705/docs/voluntary-drug-testing-policy.md)
- [Voluntary drug testing policy procedures](https://github.com/ministryofjustice/security-guidance/blob/voluntaryPolicy0705/docs/voluntary-drug-testing-policy-procedures.md)

A complete set of all the changes in this publication is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...voluntaryPolicy0705).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. I actually read this last week and forgot to finally approve. Very interesting and not an area I knew much about

**Comment by warmanaMOJ** [comment]
Thank you, published.
