### ISSUE TITLE
Request Approval to Publish guidance on Personnel Risk Assessment

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#179]
Hello @L-Crosby 

Please may I request approval to publish new guidance on Personnel Risk Assessment?

The content has been provided by Group Security, reviewed by them.

A preview of the new material can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/personnelRisk0706/docs/personnel-risk-assessment.md).

A complete set of the changes introduced with this RAP is [here](https://github.com/ministryofjustice/security-guidance/compare/main...personnelRisk0706).

NB: The new material includes a diagram. The content includes a description of the diagram for accessibility purposes.

Many thanks.

**Comment by L-Crosby** [comment]
Approved. Found the diagram helpful and like the accessibility measures.

**Comment by warmanaMOJ** [comment]
Thank you, published.
