### ISSUE TITLE
Request Approval to deploy encryption option for content

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#180]
Hello @cybersquirrel 

(FYI @L-Crosby )

An edge-case came up recently, where there was a potential requirement to be able to manage content within the Security Policy and Guidance repository, but the material was sensitive and therefore would require more careful handling. In particular, we would want to ensure that the content was *not* publicly visible, and further that it would be possible to identify who would have access granted on a case-by-base basis.

As investigation into the edge case progressed, it became clear that refinements to the requirement meant that the specific edge case no longer applied.

However, it is entirely possible that in the future, similar edge cases might arise. Therefore, it would be helpful to get approval to deploy the solution proposal we identified anyway, in anticipation of saving time in the future.

In brief, the solution proposal is:

- To deploy the [git-crypt](https://github.com/AGWA/git-crypt) encryption mechanism within this security-guidance repository.
- To create a dedicated `encrypted` folder, to hold any and all instances of content that requires management within the repository but which must also be protected against public visibility.
- To grant access to the encrypted content on a case-by-case basis, by use of individual GPG keys, thereby avoiding the need to share the actual encryption keys used.
- To protect only a very small number of 'edge case' files using this solution; if the number of protected files were to exceed 5% of content (by simple file count), this would trigger a review of the solution to determine if it was still suitable.

The proposal has been shared with Operational Security, and all comments addressed.

The complete set of deployment materials, including two small sample text files, can be previewed [here](https://github.com/ministryofjustice/security-guidance/compare/main...cryptBaseline0624). The two sample files are in the proposed `encrypted` folder ([here](https://github.com/ministryofjustice/security-guidance/tree/cryptBaseline0624/encrypted)), and cannot be read without being granted access.

Many thanks.

**Comment by cybersquirrel** [comment]
This is - as ever - very well thought through, and I am happy to approve this.

**Comment by warmanaMOJ** [comment]
Thank you, published.
