### ISSUE TITLE
Request Approval to Publish 'Back to the Office' security guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#183]
Hello @L-Crosby 

Please may I request approval to publish two Back to the Office guidance documents?

Both will be published on Know-The-Thing and offered through the Intranet, rather than GitHub pages. However, the content has been stored within GitHub for review and approval purposes (to maintain our change and publication control process).

The two documents are available for preview:

- Coming Back to the Office Securely [KTT](https://justiceuk.sharepoint.com/sites/knowthething/SitePages/Coming-Back-to-the-Office-Securely.aspx) and [GitHub](https://github.com/ministryofjustice/security-guidance/blob/culture0622/ktt/coming-back-to-the-office-securely.md).
- Secure Working Checklist [KTT](https://justiceuk.sharepoint.com/:u:/r/sites/knowthething/SitePages/Secure-working-checklist.aspx) and [GitHub](https://github.com/ministryofjustice/security-guidance/blob/culture0622/ktt/secure-working-checklist.md).

Many thanks.

**Comment by L-Crosby** [comment]
Access denied to the Sharepoint KTT link but I will check Github

**Comment by L-Crosby** [comment]
Comfortable with this and thanks to you and your fantastic team I saw and commented on this material in production. Approved.

**Comment by warmanaMOJ** [comment]
@L-Crosby : Thank you very much.
@tomdMOJ : Please publish the content on KTT, and advise when complete, thank you.

**Comment by warmanaMOJ** [comment]
Content now published, thank you.
