### ISSUE TITLE
Request Approval to Publish update to Acceptable Use Policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#184]
Hello @L-Crosby 

Please may I request approval to publish an update to the AUP page, to fix some broken links? There are no actual policy content changes.

A preview of the corrected page is available [here](https://github.com/ministryofjustice/security-guidance/blob/aupLinks0713/docs/acceptable-use-policy.md).

A full set of the changes in this fix is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...aupLinks0713).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by L-Crosby** [comment]
As a sidenote. Should I be able to see markup like POL.ITAUP.002 in the previews?

**Comment by L-Crosby** [comment]
Cool :-)

**Comment by warmanaMOJ** [comment]
Thank you, published.
