### ISSUE TITLE
Request Approval to Publish Ongoing Personnel Security guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#185]
Hello @L-Crosby 

Please may I request approval to publish new and updated Ongoing Personnel Security guidance? The material has been supplied and reviewed by Group Security.

The new page is [Ongoing personnel security](https://github.com/ministryofjustice/security-guidance/blob/ongoing0708/docs/ongoing-personnel-security.md).
The updated page is already on the Intranet, and is being retro-fitted into the GitHub repository. The page is [Reporting personal circumstance changes](https://github.com/ministryofjustice/security-guidance/blob/ongoing0708/docs/reporting-personal-circumstance-changes.md).

A full set of the changes in this request is [here](https://github.com/ministryofjustice/security-guidance/compare/main...ongoing0708).

Many thanks.

**Comment by L-Crosby** [comment]
This is really useful guidance. Thanks. Approved.

**Comment by warmanaMOJ** [comment]
Thank you, published.
