### ISSUE TITLE
Request Approval to Publish security guidance glossary

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#186]
Hello @L-Crosby 

There is a requirement for some upcoming content (on incident management) to have clear and precise use of some terminology. We have created a specific 'glossary' page that will contain the terms, and can also be used for future terminology clarification. We also link out to a wider MoJ Acronym list, for reference purposes.

Please may I request approval to publish the initial glossary page (preview [here](https://github.com/ministryofjustice/security-guidance/blob/glossary0715/docs/glossary.md))?

The glossary also appears as a link from the main content (preview [here](https://github.com/ministryofjustice/security-guidance/blob/glossary0715/docs/cyber-and-technical-security-guidance.md#other-guidance)).

 A full set of the changes requested is [here](https://github.com/ministryofjustice/security-guidance/compare/main...glossary0715).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. A small point is that I wonder if the definition for 'customer' needs to be put in more of an MoJ/public centre context. Not a showstopper but one to consider.

**Comment by warmanaMOJ** [comment]
Thank you, published.
