### ISSUE TITLE
Request Approval to Publish guidance on Ransomware.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#187]
Hello @L-Crosby 

Please may I request approval to publish new guidance on Ransomware?

A preview of the content may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/ransomware0705/docs/ransomware.md).

A full set of the changes in this publication is [here](https://github.com/ministryofjustice/security-guidance/compare/main...ransomware0705).

Many thanks.

**Comment by L-Crosby** [comment]
This is really clear and user-friendly guidance. Happy to approve.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://ministryofjustice.github.io/security-guidance/ransomware/#ransomware).
