### ISSUE TITLE
Request Approval to Publish updated guidance on Training and Education

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#188]
Hello @L-Crosby 

Please may I request approval to publish updated guidance on security training and education. This update highlights the importance of the 'Responsible for Information' requirement.

A preview of the updated content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/train0323/docs/training-and-education.md).

A full set of the changes introduced with this update is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...train0323).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://ministryofjustice.github.io/security-guidance/training-and-education/#overview).
