### ISSUE TITLE
Request Approval to Publish standardisation of Service Desk terminology

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#189]
Hello @L-Crosby 

We had a request to refrain from using the term 'help desk'; instead we should refer to 'IT Service Desk'.

Please would you approve publication of updates to standardise on the term 'IT Service Desk'.

An example of the change can be seen in the email guidance. The current published text is [here](https://ministryofjustice.github.io/security-guidance/email/#avoiding-the-problem), in step number 1. A preview of the standardised text can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/helpdesk0722/docs/email.md#avoiding-the-problem).

A full set of the changes introduced in this publication is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...helpdesk0722).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. Two questions out of interest: 
1. What is the rationale for the change? 
2. I am assuming that this was super easy due to the structure of our docs and DITA to do a find and replace. Is that right?

**Comment by warmanaMOJ** [comment]
(Questions answered via DM.)

Thank you, published.
