### ISSUE TITLE
Request Approval to Publish new guidance on secure disposal of physical equipment

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#191]
Hello @L-Crosby 

Please may I request approval to publish new material on secure disposal of physical equipment?

You can see a preview of the new material [here](https://github.com/ministryofjustice/security-guidance/blob/physicalDisposal0715/docs/secure-disposal-of-it-physical-and-on-premise.md).

There are some minor structural changes to the content, to accommodate this new material and also prepare for further additional material.

A full set of the changes included in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...physicalDisposal0715).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://ministryofjustice.github.io/security-guidance/secure-disposal-of-it-physical-and-on-premise/#secure-disposal-of-it---physical-and-on-premise).
