### ISSUE TITLE
Request Approval to Publish updated guidance on PINs and MFA

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#192]
Hello @L-Crosby 

Please may I request approval to publish some updated guidance, following a request from Operational Security?

Specifically, additional information was requested regarding the use of PINs for devices that do not support full passwords, along with clarification regarding MFA. The resulting draft material has been reviewed and checked by OST.

The main change can be previewed in the new section in passwords, containing guidance on PINS, [here](https://github.com/ministryofjustice/security-guidance/blob/pin0721/docs/passwords.md#best-pin-practices-for-everyone).

A full set of the changes introduced in this publication - including some stylistic and readability improvements - is [here](https://github.com/ministryofjustice/security-guidance/compare/main...pin0721).

Many thanks.

**Comment by L-Crosby** [comment]
Looks very sensible to me. Approved.

**Comment by warmanaMOJ** [comment]
Thank you. Published.
