### ISSUE TITLE
Request Approval to Publish upgrade guidance on (not) emailing to personal accounts

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#193]
Hello @L-Crosby 

Please may I request approval to publish updated guidance about not sending work emails to personal accounts or devices?

This update required quite a few changes to various files, for consistency, but the main content work can be previewed as follows:

- Substantial restructuring and emphasis added regarding OffSen, in particular not emailing OffSen material to personal email accounts [here](https://github.com/ministryofjustice/security-guidance/blob/email0723/docs/official-official-sensitive.md#official-sensitive).
- Added material about considering the context [here](https://github.com/ministryofjustice/security-guidance/blob/email0723/docs/official-official-sensitive.md#context).

Several files were also modified for greater consistency in how quote marks are represented.

A full set of the changes introduced in this update can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...email0723).

Many thanks.

**Comment by L-Crosby** [comment]
Great. This is excellent work to improve our policies based on feedback.

**Comment by L-Crosby** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you, published.
