### ISSUE TITLE
Request Approval to Publish clarified email guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#196]
Hello @L-Crosby 

Please may I request approval to publish some clarification guidance regarding emails?

The updated material provides links to the general email guidance (for all users), and to the more detailed email security guide (for technical users). A preview of the updated section can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/addEmail0810/docs/it-security-all-users-policy.md#email-security).

A full set of the changes in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...addEmail0810).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, published.
