### ISSUE TITLE
Request Approval to Publish CCTV policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#198]
Hello @L-Crosby

Please may I request approval to publish new physical security documentation, specifically the CCTV policy. The material has been supplied by Group Security; the current draft (preview [here](https://github.com/ministryofjustice/security-guidance/blob/cctv0803/docs/cctv-policy.md)) has been checked by them.

Note that the new content contains links to download a policy document in docx format; the document is also included in this publication request.

A full set of the changes proposed in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...cctv0803).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/cctv-policy/#cctv-policy).
