### ISSUE TITLE
Request Approval to Publish updated guidance on Accessing MoJ IT resources from overseas

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#201]
Hello @L-Crosby

Please may I request approval to publish updated guidance on Accessing MoJ IT resources from overseas? The material has been revised following feedback from Operational Security in the light of incoming questions; the current draft (preview [here](https://github.com/ministryofjustice/security-guidance/blob/overseas0813/docs/accessing-moj-it-systems-from-overseas.md)) has been checked by them.

A full set of the changes proposed in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...overseas0813). In addition to the main content changes in the 'accessing' guidance, a modification was made so that the 'feedback' link does not appear at the end of every section within the ePub download information; this was unnecessary as there is a feedback link at the start of the ePub document.

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/accessing-moj-it-systems-from-overseas/#accessing-ministry-of-justice-moj-it-systems-overseas).
