### ISSUE TITLE
Request Approval to Publish updated Data Movement Form

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#202]
Hello @L-Crosby 

Please may I request approval to publish an updated Data Movement Form? The revision changes the header so that the form is described as OffSen only when completed. This means that the blank form can be hosted on an open platform or the Intranet.

The revised version can be seen as a preview [here](https://github.com/ministryofjustice/security-guidance/blob/dmf0816/docs/gs/data-movement-form.docx).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...dmf0816).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
[Published](https://security-guidance.service.justice.gov.uk/gs/data-movement-form.docx), thank you.
