### ISSUE TITLE
Request Approval to Publish Group Security information package

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#203]
Hello @L-Crosby 

The Group Security team requested a sub-set packaging of the Group Security content, suitable for download.

A preview of the newly created link can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/gs0815/docs/cyber-and-technical-security-guidance.md#offline-content). The current draft of the Group Security content can be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/gs0815/docs/moj-guidance-gs.pdf).

This publication does not contain new material; it is an additional packaging of a subset of existing content.

A full set of the changes in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...gs0815). All the changes are associated with the build process, to create the new deliverable PDF and ePub files.

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/#offline-content).
