### ISSUE TITLE
Request Approval to Publish Change Log and RSS/Atom feeds

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#204]
Hello @L-Crosby 

Please may I request approval to publish the tooling and content for a Change Log page and associated feeds.

The page and feeds are regenerated during a build, based on information held in a simple CSV file (preview [here](https://github.com/ministryofjustice/security-guidance/blob/rss0817/changeLog.csv)). Previews of the feeds are [here for Atom](https://github.com/ministryofjustice/security-guidance/blob/rss0817/docs/atom.xml) and [here for RSS](https://github.com/ministryofjustice/security-guidance/blob/rss0817/docs/rss.xml). The feed structures have been validated using the [W3.org feed validator tool](https://validator.w3.org/feed/docs/howto/install_and_run.html).

A preview of the Change Log page, generated from the CSV file, is available [here](https://github.com/ministryofjustice/security-guidance/blob/rss0817/docs/changelog.md).

The Python script for dynamically creating the change log page and feeds is [here](https://github.com/ministryofjustice/security-guidance/blob/rss0817/buildUtils/generateRSS.py).

Lastly, a complete set of all the changes introduced in this publication is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...rss0817).

This publication does not introduce significant new or changed content, however the ongoing availability of change and update information should prove very helpful.

Thank you.

**Comment by L-Crosby** [comment]
As discussed by email, very happy with this. Approved. A nice innovation

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/#change-log).

**Comment by L-Crosby** [comment]
Approved. As discussed by email, I think this is a really interesting new feature.
