### ISSUE TITLE
Request Approval to Publish update to general app guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#205]
Hello @L-Crosby 

Following feedback in the MoJ Slack discussion, an update to the general app guidance was suggested, specifically to include Trello.

A preview of the updated guidance is available [here](https://github.com/ministryofjustice/security-guidance/blob/zoom0819/docs/general-user-video-and-messaging-apps-guidance.md#approved-tools).

A full set of the changes introduced in this update is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...zoom0819).

Please may I request approval to publish?

Many thanks.

**Comment by L-Crosby** [comment]
Hi Adrian, 
This change does not appear to include the change we discussed with Andy Philpotts yesterday. Does it need to?

**Comment by warmanaMOJ** [comment]
Those changes are in a separate branch - you can see that preview [here](https://github.com/ministryofjustice/security-guidance/blob/offSen0819/docs/general-user-video-and-messaging-apps-guidance.md#approved-tools).

Normally, I'd keep changes distinct, even if they overlap somewhat. In this case, I've combined the two branches now.

So, as a revision to the RAP request...

A preview of the updated general apps guidance may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/zoom0819/docs/general-user-video-and-messaging-apps-guidance.md#approved-tools). It includes clarification over MoJ use being approved for Official or Official Sensitive content, and also details for use of Trello.

A full set of the changes in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...zoom0819).

Please may I request approval to publish?

Many thanks.

**Comment by L-Crosby** [comment]
Approved. Thanks for the clarification.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/general-user-video-and-messaging-apps-guidance/#approved-tools).
