### ISSUE TITLE
Request Approval to Publish revised content header

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#206]
Hello @L-Crosby 

(cc FYI @cybersquirrel )

Further to the recent email exchanges...

I have been working on updating the header content for pages in the security guidance publication. This is to better align with the formal guidance on [design patterns for headers](https://design-system.service.gov.uk/components/header/). The proposed changes have been reviewed and OK'd by a a Senior MoJ Interaction Designer.

Normally, I'd include a link to preview the changes, but in this case the preview rendering can't show the changes until it goes live. However, I have previously supplied screenshots in the aforementioned email exchanges.

A complete set of all the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...logo0818).

Please may I request approval to publish?

Many thanks.

**Comment by L-Crosby** [comment]
Approved as per previous email conversation. Thanks

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/).
