### ISSUE TITLE
Request Approval to Publish additional guidance for remote working

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#208]
Hello @L-Crosby 

Following some feedback from Operational Security, we've added some extra requirements and tips into the Remote Working guidance. The updates provide additional recommendations and best practices for safer working.

Please may I request approval to publish these updates?

A preview of the changes can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/gib0902/docs/remote-working.md#protecting-your-workspace-and-equipment), with additions to both the 'you must' and 'you must not' sections.

This publication also includes some stylistic improvements to the 'clear screen and desk' content [here](https://github.com/ministryofjustice/security-guidance/blob/gib0902/docs/clear-screen-and-desk.md), some minor implementation patches for the hosting system, and a correction to a typo in an abbreviation.

A full set of all the changes in this publication is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...gib0902).

Many thanks.

**Comment by L-Crosby** [comment]
- The link to the 'clear desk policy' guidance is labelled '**clean**desk policy. I assume this is a typo

**Comment by L-Crosby** [comment]
On the clear screen policy, do we want to suggest people should keep their desk top tidy and not have anything labelled sensitive displayed on their desktop or any sensitive files. The wording needs to be thought about so this might be a later addition.

**Comment by L-Crosby** [comment]
Is the clear desk/screen policy a good place to remind people to 'think before they print'?

**Comment by L-Crosby** [comment]
Approved as is but with recommended additions/changes for later versions.

**Comment by warmanaMOJ** [comment]
Thank you, I've fixed each point as per your great feedback:

- Clean desk -> Clear desk typo [fixed](https://github.com/ministryofjustice/security-guidance/blob/gib0902/docs/remote-working.md#protecting-your-workspace-and-equipment).
- [Added](https://github.com/ministryofjustice/security-guidance/blob/gib0902/docs/clear-screen-and-desk.md#clear-screen) advisory about not having anything sensitive on the desktop.
- [Added](https://github.com/ministryofjustice/security-guidance/blob/gib0902/docs/clear-screen-and-desk.md#clear-screen-and-desk) reminder and [paragraph](https://github.com/ministryofjustice/security-guidance/blob/gib0902/docs/clear-screen-and-desk.md#clear-desk) about thinking before printing.

**Comment by L-Crosby** [comment]
Excellent. Reviewed and approved without qualification.

**Comment by warmanaMOJ** [comment]
Thank you. [Published](https://security-guidance.service.justice.gov.uk/remote-working/#protecting-your-workspace-and-equipment).
