### ISSUE TITLE
Request Approval to Publish policy on protests and demonstrations

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#209]
Hello @cybersquirrel 

(FYI @L-Crosby )

Please may I request approval to publish new policy and guidance on public protests and demonstrations? The content was provided by Group Security, and the draft reviewed by them.

The preview of the new content is available [here](https://github.com/ministryofjustice/security-guidance/blob/publicProtest0901/docs/public-protest-and-demonstrations-policy.md).

A full set of the changes introduced in this publication is available [here](https://github.com/ministryofjustice/security-guidance/compare/main...publicProtest0901).

Many thanks.

**Comment by cybersquirrel** [comment]
Hi - can I check if this has been reviewed by legal? The only other comment I had was whether we should remove the generic 'contact' bit at the bottom for this material, as questions need to head to Group Security. Happy to approve otherwise. Thank you!

**Comment by warmanaMOJ** [comment]
Good question. Checking upstream...

**Comment by warmanaMOJ** [comment]
@L-Crosby 

Please would you review and approve this publication? In answer to Jon's question, the content has been reviewed by Legal, who were content. A copy of their response is recorded in the internal task card.

Many thanks.

**Comment by L-Crosby** [comment]
I remember why I didn't approve this straight away. I meant to ask about Jon's other question. _The only other comment I had was whether we should remove the generic 'contact' bit at the bottom for this material, as questions need to head to Group Security._

I think this is sensible and we should direct people to group security rather than cyber consultancy. Once this is answered I will be able to approve

**Comment by warmanaMOJ** [comment]
Thank you - the link to general contact has now been removed, in favour of the [link to Group Security](https://github.com/ministryofjustice/security-guidance/blob/publicProtest0901/docs/public-protest-and-demonstrations-policy.md#physical-security-advice).

**Comment by L-Crosby** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/public-protest-and-demonstrations-policy/#public-protest-and-demonstrations-policy).
