### ISSUE TITLE
Request Approval to Publish guidance on National Security Vetting contacts

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#210]
Hello @L-Crosby 

Please may I request approval to publish guidance on National Security Vetting contacts? Specifically, information on the role and registration process.

The information was provided by Group Security, and has been checked by them.

A preview of the material can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/nsvContacts0902/docs/national-security-vetting-contact.md).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...nsvContacts0902).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/national-security-vetting-contact/#national-security-vetting-contact).
