### ISSUE TITLE
Request Approval to Publish updates to refer to Gov007 V2

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#212]
Hello @L-Crosby 

Please may I request approval to publish updates to the security guidance references to standard Gov007, following the release of V2 of the standard?

The changes required are modest; a slight correction to the section reference numbers, and updating the cited text from the standard. A preview of the modified section can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/new0070913/docs/index.md#background).

We've also stored copies of the V1 and V2 documents, for reference purposes.

A complete set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...new0070913).

Many thanks.

**Comment by L-Crosby** [comment]
Thanks for setting things out so clearly. Approved.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/#background).
