### ISSUE TITLE
Request Approval to Publish demo HMCTS file.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#215]
Hello @fishihmcts 

Please may I request approval to publish updated content.

The content may be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/hmcts0914/docs/hmcts/sample.md).

Many thanks.

**Comment by fishihmcts** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Closing the issue; content is now [live](https://security-guidance.service.justice.gov.uk/hmcts/sample/#sample-file).
