### ISSUE TITLE
Request Approval to Publish HMCTS Vetting and Clearance Policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#220]
Hello @fishihmcts 

Please may I request approval to publish the HMCTS vetting and clearance policy?

A preview of the content may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/hmcts0916/docs/hmcts/vetting-and-clearance-policy.md).

Many thanks.

**Comment by fishihmcts** [comment]
Hello @warmanaMOJ -  Approved with thanks

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/hmcts/vetting-and-clearance-policy/).
