### ISSUE TITLE
Request Approval to Publish typo fix

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#222]
Hello @L-Crosby 

Please may I request approval to publish a minor typo fix, reported by a user? The affected sentence should read: "Stronger passwords typically contain at least..." Currently, it reads: "[Stronger passwords typically at least...](https://security-guidance.service.justice.gov.uk/password-creation-and-authentication-guide/#password-length-and-complexity)"

A preview of the change can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/fixTypo0921/docs/password-creation-and-authentication-guide.md#password-length-and-complexity).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...fixTypo0921).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/password-creation-and-authentication-guide/#password-length-and-complexity).
