### ISSUE TITLE
Request Approval to 'Publish' content regarding use of Live Data for Testing.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#223]
Hello @L-Crosby 

We've had a request from the DP team to change some of the guidance in the topic on Using Live Data for Testing Purposes. They'll be supplying some revised material in due course, but in the interim they have asked that the DP section be removed from that topic.

Please may I request approval to publish revised content on Using Live Data for Testing Purposes? The *original* content can be seen [here](https://security-guidance.service.justice.gov.uk/using-live-data-for-testing-purposes/#data-privacy-considerations). The preview of the modified content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/dpConsiderations0923/docs/using-live-data-for-testing-purposes.md#using-live-data-for-testing-purposes).

A full set of all the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...dpConsiderations0923).

Many thanks.

**Comment by L-Crosby** [comment]
I have spoken to Jon about this. I do not really understand the logic but I am fine with this for now. Approved.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/using-live-data-for-testing-purposes/#do-you-really-need-to-use-live-data).
