### ISSUE TITLE
Request Approval to Publish update for consistency in terminology

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#224]
Hello @L-Crosby 

We had some feedback noting an inconsistency between the terms 'Information Asset Movement Form' and 'Data Movement Form'.

Please may I request approval to publish an update that corrects this problem. A preview of the revised content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/iamf0923/docs/it-acceptable-use-policy.md#removable-media).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...iamf0923).

Many thanks.

**Comment by L-Crosby** [comment]
Approve

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/it-acceptable-use-policy/#removable-media).
