### ISSUE TITLE
Request Approval to Publish guidance on public wifi

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#225]
Hello @L-Crosby 

Following feedback about clarifying when we can connect to public wifi spots, such as hotels or coffee shops, some additional guidance has been added to the remote working content.

A preview of the additional clarification can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/publicWifi0927/docs/remote-working.md#using-public-wifi-or-internet),

This publication also includes a small number of spelling corrections, and a minor security update to one of the build components.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...publicWifi0927).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/remote-working/#using-public-wifi-or-internet-and-home-broadband).
