### ISSUE TITLE
Request Approval to Publish clarification on certificate guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#228]
Hello @L-Crosby 

Please may I request approval to publish an update to the guidance on using certificates.

A preview of the new content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/clientCert1005/docs/automated-certificate-renewal.md#automated-certificate-renewal).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...clientCert1005).

Many thanks.

**Comment by L-Crosby** [comment]
Approved.

**Comment by L-Crosby** [comment]
I wouldn't mind understand at some stage what triggered the change. Happy to talk offline about that.

**Comment by warmanaMOJ** [comment]
An easy one - a great discussion in the Slack #security channel, here<https://mojdt.slack.com/archives/C52LPHPK8/p1633424643147600>.

Thanks,

Adrian

Adrian R. Warman, B.Sc., Ph.D.
Principal Cyber Security Consultant
Security, Services, and Information Governance Group
Ministry of Justice Digital and Technology
***@***.***

Next planned leave (all dates inclusive):
N/A


________________________________

**Comment by L-Crosby** [comment]
Thanks. Perfect!

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/automated-certificate-renewal/#automated-certificate-renewal).
