### ISSUE TITLE
Request Approval to Publish Domain Name policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#232]
Hello @cybersquirrel 

(FYI @L-Crosby )

Please may I request approval to publish fresh policy on MoJ Domain names? A preview of the content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/domain1007/docs/domain-names-policy.md).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...domain1007).

Many thanks.

**Comment by L-Crosby** [comment]
Approved following a walkthrough/discussion. Conditional approval given based on changing SHOULD to SHALL in statement 21.

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/domain-names-policy/#domain-names-and-domain-name-system-dns-security-policy).
