### ISSUE TITLE
Request Approval to Publish guidance on baselines for Azure subscriptions

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#238]
Hello @L-Crosby 

(cc @paul-homer )

Please may I request approval to publish new guidance for Azure subscriptions. A preview of the content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/azure0914/docs/baseline-for-azure-accounts.md).

A full set of the changes in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...azure0914).

Many thanks.

**Comment by paul-homer** [comment]
Hi Adrian,

  Thank you for your help over the last few weeks, much appreciated...

  Thanks

  Paul Homer

**Comment by warmanaMOJ** [comment]
You are most welcome - and thank _you_ for your patience! :-)
