### ISSUE TITLE
Request Approval to Publish guidance on the security clearance appeals procedures

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#239]
Hello @L-Crosby 

Please may I request approval to publish new guidance on the security clearance appeals procedures. The material was originally supplied by Group Security. A preview of the content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/sensitive1012/docs/security-clearance-appeals-procedures.md).

A full set of the changes introduced in this publication - including a downloadable version of the appeals form - can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...sensitive1012).

(You might notice that the branch for this work is called `sensitive1012`. There is nothing sensitive about the proposed content - it has been carefully checked to ensure that the material is appropriate for publication.)

Many thanks.

**Comment by L-Crosby** [comment]
Thanks for the clarification on the sensitive marking.
