### ISSUE TITLE
Request Approval to Publish clarification for remote working guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#243]
Hello @L-Crosby 

Following some great feedback from @davidread (thanks David!), we've updated the remote working guidance to improve the clarity. Essentially, the advice is now more clearly tagged with **Do** or **Do not** advisories. This also means we've been able to reduce the use of the 'policy' phrases such as **SHALL** or **SHOULD**.

Please may I request approval to publish this update?

A preview of the revised content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/doNot1018/docs/remote-working.md).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...doNot1018).

Many thanks.

**Comment by L-Crosby** [comment]
Can I just confirm this seems like a change to our policy position from advising people to avoid the use of public wifi to directly telling users not to use it? Is this the policy intent?

**Comment by warmanaMOJ** [comment]
Good point - I have corrected this in the draft.

**Comment by warmanaMOJ** [comment]
Content [published](https://github.com/ministryofjustice/security-guidance/issues/243).
