### ISSUE TITLE
Request Approval to Publish Email Blocklist Policy and Process guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#244]
Hello @cybersquirrel 

(cc FYI @L-Crosby )

We had a request from OST to publish policy and process information regarding email blocklists. The material has been reviewed by them.

Please may I request approval to publish policy and process documents. The two topics may be seen in preview [here](https://github.com/ministryofjustice/security-guidance/blob/emailBlocklists0921/docs/email-blocklist-policy.md) and [here](https://github.com/ministryofjustice/security-guidance/blob/emailBlocklists0921/docs/email-blocklist-process.md), respectively.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...emailBlocklists0921).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/email-blocklist-policy/#email-blocking-policy).
