### ISSUE TITLE
Request Approval to Publish policy on working with paper-based information.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#246]
Hello @cybersquirrel 

(cc FYI @L-Crosby )

Please may I request approval to publish policy on working with paper-based information? The guidance was originally supplied by Group Security, and the content has been reviewed by them. A preview of the draft can be see [here](https://github.com/ministryofjustice/security-guidance/blob/paper0903/docs/working-securely-with-paper-documents-and-files.md#working-securely-with-paper-documents-and-files).

A full set of all the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...paper0903).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you. Content [published](https://security-guidance.service.justice.gov.uk/working-securely-with-paper-documents-and-files/#working-securely-with-paper-documents-and-files).
