### ISSUE TITLE
Request Approval to Publish updated CCTV policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#248]
Hello @cybersquirrel 

(cc FYI @L-Crosby )

Please may I request approval to publish an updated CCTV policy document, as supplied and reviewed by Group Security.

A preview of the content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/cctv1028/gs/MoJ_CCTV_Policy.docx).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...cctv1028).

Many thanks.

**Comment by L-Crosby** [comment]
Approve

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/cctv-policy/#cctv-policy).
