### ISSUE TITLE
Request Approval to Publish accessibility and style improvements

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#249]
Hello @L-Crosby 

Please may I request approval to publish a large number of accessibility and style improvements?

I have sent a separate email providing more detail about the context of the changes.

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...intranet1104).

Many thanks.

**Comment by L-Crosby** [comment]
Approved as discussed by email

**Comment by warmanaMOJ** [comment]
Thank you, published.
