### ISSUE TITLE
Request Approval to Publish updated Acceptable Use Policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#250]
Hello @L-Crosby 

Please may I request approval to publish updated and consolidated AUP material. The two main changes are to provide more detail on monitoring of systems and information (preview [here](https://github.com/ministryofjustice/security-guidance/blob/personalData0804/docs/acceptable-use-policy.md#monitoring-of-communications)) and to clarify the situation regarding Data Protection and the storage or processing of information outside the UK (preview [here](https://github.com/ministryofjustice/security-guidance/blob/personalData0804/docs/acceptable-use-policy.md#data-protection-considerations)). The latter update has been created with assistance from the DP team, and the draft has been updated with their feedback.

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...personalData0804).

Many thanks.

**Comment by L-Crosby** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/acceptable-use-policy/#acceptable-use-policy).
