### ISSUE TITLE
Request Approval to Publish corrected System Backup Policy

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#251]
Hello @L-Crosby 

Please may I request approval to publish corrections to the System Backup Policy, and associated supporting content?

We had some feedback advising that a couple of links in the backup policy were broken. A draft of the changed document with the corrected links may be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/backup1102/docs/system-backup-policy.md#technical-controls).

While fixing the problem, it became clear that a more resilient and long-term fix would be to include the Technical Controls Policy (TCP) into the security guidance. The TCP is already published on the Intranet: `https://intranet.justice.gov.uk/documents/2015/04/technical-controls-policy.pdf`. The same content, reformatted for inclusion in the security guidance built, may be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/backup1102/docs/technical-controls-policy.md#technical-controls-policy).

A number of structural changes have also been introduced, to help improve user access and cross-referencing between related topics.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...backup1102).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. All seems very sensible to me.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/system-backup-policy/#system-backup-policy).
