### ISSUE TITLE
Request Approval to Publish updated guidance on Government Classification Scheme

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#252]
Hello @L-Crosby 

Following a request from Group Security to update the Government Classification Scheme information, please may I request approval to publish updated material. A preview of the updated content, which has been reviewed by Group Security, may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/gcs0910/docs/government-classification-scheme.md).

This new material makes the [currently published](https://security-guidance.service.justice.gov.uk/official-official-sensitive/) information about `OFFICIAL` and other classifications obsolete. In this publication, the old page is removed, and a redirect enabled so that if anyone had bookmarked the old page, they are automatically taken to the updated page.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...gcs0910).

Many thanks.

**Comment by L-Crosby** [comment]
Approved.

**Comment by L-Crosby** [comment]
Can I ask whether this comes from official guidance or is bespoke to the MoJ as some of it could do with a review (in the longer term) for readability and accessibility of language?

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/government-classification-scheme/#government-classification-scheme).

The content is provided from official guidance. Yes, it could indeed be improved; however, there is a separate task underway that would enable us to revisit this anyway. So, yes, it will be picked up again in the near future.
