### ISSUE TITLE
Request Approval to Publish guidance on sending information securely

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#253]
Hello @L-Crosby 

Please may I request approval to publish guidance supplied by Group Security, regarding sending information securely?

A preview of the content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/sending1026/docs/sending-information-securely.md).

A full set of the changes introduced by this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...sending1026).

Many thanks.

**Comment by L-Crosby** [comment]
Approved.

**Comment by L-Crosby** [comment]
As a non-essential question - not preventing approval - where we say 'If the person or organisation you are sending the information to is outside departmental OFFICIAL or CJSM networks, you SHALL consider the sensitivity of the information. It might be safer to send it on encrypted removable media or in hardcopy. - Might we also suggest using a secure dropbox or storing it in a secure location where it can be accessed. The caveats around this might take too much explaining but it is worth exploring.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/sending-information-securely/#sending-information-securely).

Your notes about using a secure dropbox, etc., have been captured into a fresh task to enhance the published material.
