### ISSUE TITLE
Request Approval to Publish updated guidance on personal devices

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#254]
Hello @L-Crosby 

Following useful feedback and discussion regarding use of personal devices, please may I request approval to publish some updated guidance about using a personal device to connect to a business Teams meeting as a Guest?

A preview of the updated section can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/personal1111/docs/personal-devices.md#guidance).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...personal1111).

Many thanks.

**Comment by L-Crosby** [comment]
Very sensible. Approved.

**Comment by warmanaMOJ** [comment]
Many thanks, [published](https://security-guidance.service.justice.gov.uk/personal-devices/#guidance).
