### ISSUE TITLE
Request Approval to Publish fresh guidance on security in the office

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#255]
Hello @L-Crosby 

Please may I request approval to publish new guidance on working in the office. The content was supplied by Group Security. A preview of the content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/office1111/docs/security-in-the-office.md).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...office1111).

Many thanks.

**Comment by L-Crosby** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/security-in-the-office/#security-in-the-office).
