### ISSUE TITLE
Request Approval to Publish updated structure for Other Guidance links

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#258]
Hello @L-Crosby,

Please may I request approval to publish an update to the structure of the Other Guidance content.

A preview of the revised structure may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/subheadings1116/docs/index.md#other-guidance).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...subheadings1116).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/#other-guidance).
