### ISSUE TITLE
Request Approval to Publish clarification on MFA guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#259]
Hello @L-Crosby,

Following feedback, we've added a note to the guidance on MAF, advising that an MFA one-time code must not be sent to a shared device or account. but can only be sent to an individual device/account. A preview of the added note may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/mfa1122/docs/multi-factor-authentication-mfa-guide.md#mfa) (after the list of MFA options).

There are also some cross-referencing stylistic improvements, to aid identification of related information.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...mfa1122).

Many thanks.

**Comment by L-Crosby** [comment]
Very staightforward and easy to follow changes. Approved.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/multi-factor-authentication-mfa-guide/#mfa).
