### ISSUE TITLE
Request Approval to Publish updated guidance on personal devices

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#261]
Hello @L-Crosby

Following interesting discussions and feedback about Bluetooth connected devices, we've updated the guidance on what constitutes personal devices. In particular, we now address Bluetooth connected vehicles.

A preview of the updated material may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/personal1123/docs/personal-devices.md#overview)(in the note), and also the new section on Connected vehicles [here](https://github.com/ministryofjustice/security-guidance/blob/personal1123/docs/personal-devices.md#connected-vehicles).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...personal1123).

Please may I request approval to publish this update?

Many thanks.

**Comment by L-Crosby** [comment]
Approved. Would be interested to know the origins of these changes.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/personal-devices/#personal-devices).
