### ISSUE TITLE
Request Approval to Publish updated application form for National Security Vetting Contact

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#262]
Hello @L-Crosby,

Please may I request approval to publish an updated application form for candidates to become a National Security Vetting Contact. The new form is a PDF supplied by Group Security, and replaces an earlier Word document.

The form is accessed through the links [here](https://github.com/ministryofjustice/security-guidance/blob/nsvc1201/docs/national-security-vetting-contact.md#downloads). The preview for the new form is accessible [here](https://github.com/ministryofjustice/security-guidance/blob/nsvc1201/docs/gs/national-security-vetting-contact-form.pdf).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...nsvc1201).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, published.
