### ISSUE TITLE
Request Approval to Publish guidance on MTA-STS and TLS-RPT

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#263]
Hello @cybersquirrel 

(FYI @L-Crosby)

Please may I request approval to publish updated guidance on email authentication and checking, specifically the addition of guidance regarding MTA-SLS and TLS-RPT?

A preview of the new content sections may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/mta1201/docs/email-authentication-guide.md#mail-transfer-agent-strict-transport-security) and [here](https://github.com/ministryofjustice/security-guidance/blob/mta1201/docs/email-authentication-guide.md#tls-reporting), respectively.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...mta1201).

Many thanks.

**Comment by cybersquirrel** [comment]
Hello,

Thanks for quick turn-around on this.

One question - should we not be saying something marginally stronger on these points, namely that it is our policy to follow the HMG Email Security policy for MTA-STS etc, and have it deployed in 'enforce' mode? You could deploy in 'none' mode and technically meet the policy requirement I think?

Jon.

**Comment by warmanaMOJ** [comment]
Hello @cybersquirrel 

Thank you - I've updated the draft, accordingly, in particular emphasising the alignment with HMG Email Security policy [here](https://github.com/ministryofjustice/security-guidance/blob/mta1201/docs/email-authentication-guide.md#email-authentication-guide) and requiring the use of `endorse` mode ([here](https://github.com/ministryofjustice/security-guidance/blob/mta1201/docs/email-authentication-guide.md#mail-transfer-agent-strict-transport-security)).

Many thanks.

**Comment by cybersquirrel** [comment]
These edits completely address my comments, happy to approve publication.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/email-authentication-guide/).
