### ISSUE TITLE
Request Approval to Publish update to Accessing MoJ Systems from Overseas

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#264]
Hello @L-Crosby,

Please may I request approval to publish a small update to the above guidance? Specifically, we've added a link to some supplementary guidance on the MoJ Intranet.

A preview of the new paragraph can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/overseas1207/docs/accessing-moj-it-systems-from-overseas.md#accessing-moj-it-systems-from-overseas).

A full set of the changes in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...overseas1207).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/accessing-moj-it-systems-from-overseas/).
