### ISSUE TITLE
Request Approval to Publish clarification about access to email accounts

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#265]
Hello @cybersquirrel 

(FYI @L-Crosby )

Please may I request approval to publish a clarification regarding when access is permitted to a user's business email account. The clarification follows a discussion within the security team. In essence, the clarification is that access is permitted when an investigation that requires has started. An additional scenario is where the access is required to enable and maintain corporate memory.

A preview of the changes can be seen in the Authorised Access section [here](https://github.com/ministryofjustice/security-guidance/blob/emailAccess1207/docs/email-security-guide.md#authorised-access-to-user-accounts).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...emailAccess1207).

Many thanks.

**Comment by cybersquirrel** [comment]
These changes don't seem problematic - happy to approve.

One minor point I saw on reviewing this was I saw in the surrounding text it talks about 'employees'. Obviously - I'd hope - this text would apply to contractors and other users of our IT. This might be worth clarifying in a future edit.

Many thanks,

Jon.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/email-security-guide/#authorised-access-to-user-accounts).

Also, I've opened a ticket to check and revise content mentioning 'employees'.
