### ISSUE TITLE
Request Approval to Publish debrief requirement following return from travel

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#266]
Hello @L-Crosby ,

Following feedback from Group and Operational Security, please may I request approval to publish an additional section in the 'Accessing MoJ systems while travelling' guidance? Specifically, a new section has been included describing a security debrief that is mandatory after some travel or where other security conditions apply.

A preview of the new section may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/debrief1202/docs/accessing-moj-it-systems-from-overseas.md#on-your-return). The draft has been reviewed and updated with further feedback from Group and Operational Security.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...debrief1202).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by L-Crosby** [comment]
As an additional thought and because of recent events - do we want a question about if they noticed anything usual with their IT in the example questions.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/accessing-moj-it-systems-from-overseas/#on-your-return).

Task ticket opened to add question, as per your note.
