### ISSUE TITLE
Request Approval to Publish correction to broken link

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#267]
Hello @L-Crosby 

Please may I request approval to publish a correction to a broken link. Specifically, a link on an Intranet-only landing page for personnel clearances referred to a UK GOV page that has been removed. We now need to refer to a generic United Kingdom
Security Vetting [page](https://www.gov.uk/government/organisations/united-kingdom-security-vetting).

A preview of the corrected link may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/vettingLink1207/intranet/personnel-security-clearances.md) (under the `##National Security Clearances` heading).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...vettingLink1207).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you, [updated](https://github.com/ministryofjustice/security-guidance/blob/main/intranet/personnel-security-clearances.md).
