### ISSUE TITLE
Request Approval to Publish Security Threat level guidance, and associated emergency procedures

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#268]
Hello @L-Crosby,

(FYI @cybersquirrel )

Please may I request approval to publish new Security Threat Level guidance, and associated procedures? This material was requested by Group Security, and the draft has been reviewed by them.

A preview of the new content may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/threatLevel1209/docs/security-threat-level-and-emergency-procedures.md#security-threat-leveland-emergencyprocedures). Additionally, a link direct to the new content is being added as the new first entry in the 'quick links' section of the guidance landing page; the preview can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/threatLevel1209/docs/cyber-and-technical-security-guidance.md#popular-links).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...threatLevel1209).

Many thanks.

**Comment by L-Crosby** [comment]
Important and timely. Approved.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/security-threat-level-and-emergency-procedures/#security-threat-leveland-emergencyprocedures).
