### ISSUE TITLE
Request Approval to Publish enablement of DDG Search Engine

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#270]
Hello @cybersquirrel ,

Further to the discovery that some content (notably the wifi guidance) in the security guidance is not being indexed by Google, I have checked that there are no obvious blocks, and requested that all pages are indeed indexed. Although the request was submitted a couple of days ago, at this time the 'missing' content is still not showing up in Google.

I've modified the search facility slightly, so that by default it will go to DuckDuckGo (DDG) rather than Google. Both DDG and bing.com seem to be indexing all the content correctly.

The modification is simple, and quick to reverse when the missing content appears in Google.

There are no security guidance content changes in this request.

Please may I request approval to deploy this change?

A preview of the changes can be seen on lines 45-51, [here](https://github.com/ministryofjustice/security-guidance/blob/ddg1215/jekyll-baseline/_layouts/default.html).

A full set of the changes in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...ddg1215).

Many thanks.

**Comment by cybersquirrel** [comment]
So glad that someone spotted this problem, and you've done this to resolve it. Happy to approve.

**Comment by warmanaMOJ** [comment]
Thank you, use of DDG [enabled and tested](https://security-guidance.service.justice.gov.uk/#cyber-and-technical-security-guidance).
