### ISSUE TITLE
Request Approval to Publish awareness material on avoiding Seasonal SMS scams

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#271]
Hello @cybersquirrel ,

Please may I request approval to publish some security culture/awareness material on avoiding seasonal parcel delivery scams?

The material includes an easy-reference downloadable flyer/poster. A preview of the content can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/smsScams1218/docs/security-culture.md). The flyer/poster itself can be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/smsScams1218/docs/culture/christmas-sms-delivery-scams.pdf).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...smsScams1218).

Many thanks.

**Comment by cybersquirrel** [comment]
Lovely - happy to approve!

Seasons greetings everyone! 🎅

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/security-culture/#security-culture).
