### ISSUE TITLE
Request Approval to Publish updated overseas travel and access guidance.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#272]
Hello @cybersquirrel 

Following feedback and requests from Group Security, guidance for accessing MoJ IT systems from overseas, and guidance on working while overseas, has been updated:

- Links to downloadable forms and guides now connects to the published guidance site.
- Contacts now prioritise security@... rather than one of the sub teams.
- The list of extra-attention countries has been updated to be current for December 2021.

A preview of the updated content can be seen as follows:

- [Accessing MoJ IT systems from overseas](https://github.com/ministryofjustice/security-guidance/blob/overseas1221/docs/accessing-moj-it-systems-from-overseas.md)
- [Overseas travel](https://github.com/ministryofjustice/security-guidance/blob/overseas1221/docs/overseas-travel.md)
- Updated [Overseas travel form](https://github.com/ministryofjustice/security-guidance/blob/overseas1221/docs/gs/overseas-travel-form.docx).
- Updated [Overseas travel guide](https://github.com/ministryofjustice/security-guidance/blob/overseas1221/docs/gs/overseas-travel-guide-v1-4-dec-2021.docx)

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...overseas1221).

This updated content has been reviewed and approved by Group Security/Operational Security.

Many thanks.

**Comment by cybersquirrel** [comment]
Thank you - approved.

**Comment by warmanaMOJ** [comment]
Thank you, content published [here](https://security-guidance.service.justice.gov.uk/accessing-moj-it-systems-from-overseas/).
