### ISSUE TITLE
Request Approval to publish updated copyright notices in '22

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#273]
Hello @cybersquirrel 

Please may I request approval to publish a fresh content build on, or reasonably soon after, 00:00 on January 1st 2022? The objective is to update the copyright dated material. This publication request does not include any new or modified security policy or guidance.

The build will be enabled by using new source media files. Previews of the media sources can be seen [here](https://github.com/ministryofjustice/security-guidance/tree/newYear22/srcMedia). An example build using the updated copyright information can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/newYear22/docs/moj-guidance.pdf). (View the last page of the PDF and note that the copyright date reads 2022.)

A full set of the changes introduced by this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/newYear22/docs/moj-guidance.pdf).

Many thanks.

**Comment by cybersquirrel** [comment]
I refuse to believe it can be 2022 already - 2021 only started a few weeks ago...(checks diary)...oh.  :-)

Approved.

**Comment by warmanaMOJ** [comment]
I know, scary isn't it!

Thank you, I'll update this ticket following publication.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/#offline-content).
