### ISSUE TITLE
Request Approval to Publish clarification regarding when more detailed information is required for overseas travel

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#274]
Hello @cybersquirrel ,

Please may I request approval to publish a correction to the process for determining what approvals are required for overseas travel. Specifically, a clarification that part two of the overseas process is gated _only_ on the countries involved, not whether or not someone is taking MoJ kit with them.

The correction has been checked and approved by OST.

A preview of the corrected step 4 is part one may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/overseas1223/docs/accessing-moj-it-systems-from-overseas.md#part-one).

There is also a minor change to the contact details, to direct everyone to security@... in the first instance.

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...overseas1223).

Many thanks.

**Comment by cybersquirrel** [comment]
Approved with festive good wishes to all involved.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/accessing-moj-it-systems-from-overseas/#part-one).
