### ISSUE TITLE
Request Approval to Publish correct Slack channel link

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#275]
Hello @cybersquirrel 

Please may I request approval to publish a corrected link to the Slack channel for the Data Privacy team?

A preview of the corrected channel details can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/slackLink1209/docs/general-user-video-and-messaging-apps-guidance.md#privacy-and-personal-information-data-protection).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...slackLink1209).

Many thanks.

**Comment by cybersquirrel** [comment]
Happy with this - approved.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/general-user-video-and-messaging-apps-guidance/#privacy-and-personal-information-data-protection).
