### ISSUE TITLE
Request Approval to Publish update to ITHC guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#276]
Hello @cybersquirrel 

Please may I request approval to publish updated guidance from the OST, regarding IT Health Checks?

The main change is the addition of a section on Cloud platforms. The new material may be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/ithc1230/docs/ost/ithc.md#cloud-platforms).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...ithc1230).

Many thanks.

**Comment by cybersquirrel** [comment]
Looks very sensible to me. Happy to approve.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/ost/ithc/#cloud-platforms).
