### ISSUE TITLE
Request Approval to Publish updated guidance regarding control of outbound connections

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#277]
Hello @L-Crosby,

(cc FYI @cybersquirrel )

Please may I request approval to publish an update to the guidance on locking down/hardening systems? Specifically, to address scenarios such as `log4j`, where a capability is used to request and exfiltrate information, additional guidance has been added to prevent outbound connections to random internet systems, unless this is a core part of their design. Firewall rules and other network configuration must prevent this.

A proposed addition has been made to the guidance on system lockdown and hardening, with review and input from the system development and hosting teams. A preview of the addition can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/log4j1230/docs/system-lockdown-and-hardening-standard.md#services-security-and-networking-applications) (an additional row added to the table regarding 'Initiating outbound connections').

The overall content for this topic has also been updated from its 'legacy' status to better reflect and refer to current cyber security standards and requirements.

A full set of the changes proposed in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...log4j1230).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. Thank you for the clear background info.
