### ISSUE TITLE
Request Approval to Publish updated Overseas Travel Form

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#280]
Hello @L-Crosby,

Following feedback from OST, an updated Overseas Travel request form has been created. Please may I request approval to publish this update?

The updated form may be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/formUpdate0117/docs/gs/overseas-travel-form.docx).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...formUpdate0117).

Many thanks.

**Comment by L-Crosby** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/overseas-travel/#documents).
