### ISSUE TITLE
Request Approval to Publish download link for ransomware information leaflet

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#283]
Hello @L-Crosby,

Please may I request approval to publish a link to the new ransomware information leaflet?

A preview of the link may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/ransomware0125/docs/ransomware.md#ransomware)

A full set of the changes introduced in this publication, including a copy of the leaflet itself, may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...ransomware0125).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. To note I have reviewed and commented on the leaflet prior to the formal approval process.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/ransomware/#ransomware).
