### ISSUE TITLE
Request approval to publish corrected ransomware leaflet (fixing typos)

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#284]
Hello @L-Crosby,

(As is so often the way, no sooner do we go live with some content than a set of typos jump out at us.)

Please may I request approval to publish an updated ransomware PDF, with corrected typos as follows:
From "The same year, GPcode ransomware infected" to "The same year, GPCode ransomware infected"
From "Wannacry as one of the broadest and most" to "WannaCry as one of the broadest and most"
From "attack cost the council an estimated of over" to "attack cost the council an estimate of over"
From "of bad actors guessing them and gaining" to "of threat actors guessing them and gaining"
From "Use Multi-factor Authentication (MFA) to" to "Use Multi-Factor Authentication (MFA) to"

While none of these are major or change the overall message, it would be good to have the corrected version in place.

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...ransomware0125b).

Many thanks.

**Comment by L-Crosby** [comment]
Good spot. Approved.

**Comment by warmanaMOJ** [comment]
Thank you, update published.
