### ISSUE TITLE
Request Approval to Publish emphasis on passwords guidance.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#287]
Hello @L-Crosby,

Please may I request approval to publish a small but significant paragraph in the Passwords guidance, emphasising that you should not share passwords?

A preview of the added paragraph may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/password0128/docs/passwords.md#general-best-practices) (immediately after the note).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...password0128).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. 
For the record, I was thinking about line managers/senior managers being able to approve sharing of passwords. On reflections this is probably correct and pragmatic but I felt slightly uneasy as it should not really ever be necessary.

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://github.com/ministryofjustice/security-guidance/pull/292).
