### ISSUE TITLE
Request Approval to Publish updated Glossary page

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#294]
Hello @L-Crosby ,

Please may I request approval to publish an updated security Glossary? The main changes are additional terms we are using in various security culture materials. There is also a new link to the NCSC list of terms.

To enable more flexible internal cross-referencing within the documentation, there's a new build utility (`dlTarget.py`) that parses the glossary list and generates internal tags.

A preview of the updated glossary page may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/glossary0202/docs/glossary.md#glossary).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...glossary0202).

Many thanks.

**Comment by L-Crosby** [comment]
A few comments:

**Comment by L-Crosby** [comment]
A few comment

**Comment by L-Crosby** [comment]
Approved: One comment for blue team - can we link it to the OST definition further down the document. Is is not clear from the document that blue team and OST are the same thing and that we use OST in this org.

**Comment by warmanaMOJ** [comment]
Hello @L-Crosby 

No problem. The Blue Team [entry](https://github.com/ministryofjustice/security-guidance/blob/glossary0202/docs/glossary.md#blue-team) now links across to the OST entry, and [vice versa](https://github.com/ministryofjustice/security-guidance/blob/glossary0202/docs/glossary.md#operational-security-team-ost).

Also, following further feedback, a substantial extra section of out-of-band checks has been [added](https://github.com/ministryofjustice/security-guidance/blob/glossary0202/docs/glossary.md#out-of-band-checks).

Given the substantial nature of the changes, please may I request an updated approval?

Many thanks.

**Comment by warmanaMOJ** [comment]
Thank you. Content [published](https://security-guidance.service.justice.gov.uk/glossary/).
