### ISSUE TITLE
Request Approval to Publish minor fixes.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#298]
Hello @cybersquirrel 

Please may I request approval to publish some minor fixes/improvements following feedback, namely (links to previews):

- Convert contact details from OST to security@... for example [here](https://github.com/ministryofjustice/security-guidance/blob/fixLinks0215/docs/secure-disposal-of-it-equipment.md#secure-disposal-of-it-equipment).
- Remove mention of CD shredder in 102PF, which is no longer available.
- Correction of link to [mailcheck](https://github.com/ministryofjustice/security-guidance/blob/fixLinks0215/docs/spam-and-phishing-guide.md#mail-check).
- Updates to the web hosting support tools.

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...fixLinks0215).

Many thanks.

**Comment by cybersquirrel** [comment]
Looks sensible to me. Happy to progress.

**Comment by warmanaMOJ** [comment]
Thank you, updates published.
