### ISSUE TITLE
Request Approval to update security.txt file

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#300]
Hello @cybersquirrel 

Please may I request approval to update the `security.txt` file. This change is related to the [ongoing work](https://github.com/ministryofjustice/security-guidance/issues/296) regarding the vulnerability disclosure policy.

A preview of the change (minor at this time) may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/secTxt0216/docs/.well-known/security.txt).

A full set of the changes introduced in this update may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...secTxt0216).

Many thanks.

**Comment by cybersquirrel** [comment]
LGTM

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/security.txt).
