### ISSUE TITLE
Request Approval for new phishing guidance for all users

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#302]
Hello @cybersquirrel 

Please may I request approval for new phishing guidance for all users. A preview of the new content may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/phish0211/docs/phishing-guide.md#phishing-guide).

A full set of the changes introduced may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...phish0211).

Many thanks.

**Comment by cybersquirrel** [comment]
This is great content, thank you.

A few tweaks I'd suggest:
- change this example: "A request to pay money to bail a family member out of jail." to "A request to send money urgently to a family member in trouble" (and/or) "A false request to pay money to avoid something - such as paying to avoid jury service"
- With "Companies, banks, government departments, and social media sites will never contact you and ask for your MFA code."... I get what you are saying, but also they kind of do... in that they send you legitimate emails that take you to login pages where you need to provide your MFA code. 
- "Change your password." - needs something adding about not just clicking the change password link in any associated email, but getting it via an out of band means.
- What to do if you are phished - maybe it should be "if you think you've been phished"

*really* like the tone of the last section. Spot on.

Thanks,

Jon,

**Comment by warmanaMOJ** [comment]
Thank you - really appreciate the great feedback. We've updated the [preview text](https://github.com/ministryofjustice/security-guidance/blob/phish0211/docs/phishing-guide.md#phishing-guide) accordingly.

**Comment by cybersquirrel** [comment]
Super - looks good to me!

**Comment by warmanaMOJ** [comment]
Thank you, content [published](https://security-guidance.service.justice.gov.uk/phishing-guide/).
