### ISSUE TITLE
Request review of QR code guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#309]
Hello @L-Crosby 

Please may I invite your review and feedback on new guidance about the use of QR code?

A preview of the suggested addition to the Phishing guidance can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/qr0303/docs/phishing-guide.md#qr-codes).

Many thanks.

**Comment by L-Crosby** [comment]
Perfect. Sensible and pragmatic. Approved.

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/phishing-guide/#qr-codes).
