### ISSUE TITLE
Request review of additional guidance on tools for sharing internally and externally

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#310]
Hello @L-Crosby 

Please may I request your review and feedback on some new guidance about using tools such as Egress and Galaxkey? A preview of the new section can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/egress0304/docs/general-user-video-and-messaging-apps-guidance.md#tools-for-sharing-information-internally-and-externally).

A full set of the changes introduced in this publication can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...egress0304).

Many thanks.

**Comment by L-Crosby** [comment]
As per @cybersquirrel's comments - can we clarify the bit around sharing with external organisations. Presumably team's or justice email can be used for sharing for smaller files at official:sensitive especially where they are other government departments.

**Comment by warmanaMOJ** [comment]
Hello @cybersquirrel and @L-Crosby 

Thank you for the feedback. We have revised the update to address the points you raised. You can see the results in preview [here](https://github.com/ministryofjustice/security-guidance/blob/egress0304/docs/general-user-video-and-messaging-apps-guidance.md#tools-for-sharing-information-internally-and-externally).

We have also added a [fresh section on proctoring software](https://github.com/ministryofjustice/security-guidance/blob/egress0304/docs/general-user-video-and-messaging-apps-guidance.md#proctoring-software). While normally we would treat these as two separate work branches, it was felt more efficient to incorporate both updates in one activity.

A full set of the changes may be seen [here]().

Please may I invite any further review comments?

Many thanks.

**Comment by warmanaMOJ** [comment]
Hello @cybersquirrel and @L-Crosby 

Thank you for the additional feedback. The external guidance section has been further revised to highlight the use of Teams, [here](https://github.com/ministryofjustice/security-guidance/blob/egress0304/docs/general-user-video-and-messaging-apps-guidance.md#tools-for-sharing-information-internally-and-externally).

As before, the full set of changes may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...egress0304).

Are you content with this draft?

Many thanks.

**Comment by L-Crosby** [comment]
Yes. That all looks great and all my concerns have been addressed. Approved.

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/general-user-video-and-messaging-apps-guidance/#tools-for-sharing-information-internally-and-externally).
