### ISSUE TITLE
Request review of update to LastPass guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#314]
Hello @L-Crosby 

Please may I request a review of the updates to the LastPass guidance. The changes were suggested following [PR feedback](https://github.com/ministryofjustice/security-guidance/pull/312) by the technical team. The [preview draft](https://github.com/ministryofjustice/security-guidance/blob/lastpass0310/docs/using-lastpass.md#using-lastpass-enterprise) has been reviewed and [confirmed](https://github.com/ministryofjustice/security-guidance/pull/312#issuecomment-1064036391) by them.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...lastpass0310).

Many thanks.

**Comment by warmanaMOJ** [comment]
Thank you - great catches, on both points. I've fixed item 1, and added a bit extra for item 2 [here](https://github.com/ministryofjustice/security-guidance/blob/lastpass0310/docs/using-lastpass.md#what-it-can-be-used-for).

**Comment by L-Crosby** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/using-lastpass/#who-should-use-it).
