### ISSUE TITLE
Request review of updated ransomware leaflet

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#316]
Hello @L-Crosby 

Please may I request a review of the updated ransomware leaflet? The update fixes minor typos and grammar/spelling.

A preview of the updated leaflet may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/ransomware0311/culture/ransomware-information-leaflet.pdf).

Many thanks.

**Comment by L-Crosby** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/ransomware/#ransomware).
