### ISSUE TITLE
Request Review of updated guidance on use of Slack on personal devices

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#325]
Hello @L-Crosby 

Please may I request a review of an update to personal device guidance, clarifying that personal devices shall not access Slack for work purposes.

A preview of the new section is available [here](https://github.com/ministryofjustice/security-guidance/blob/slack0321/docs/personal-devices.md#using-slack-on-personal-devices).

Many thanks.

**Comment by warmanaMOJ** [comment]
@L-Crosby 

Please may I 'nudge' this?

Many thanks.

**Comment by L-Crosby** [comment]
Approved - we need to think about how we communicate this as I know a lot of people (including myself) use slack in this way so we consider if we do a push on this. The biggest impact will be in digital and technology so we will need to engage sensibly.

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/personal-devices/#using-moj-tools-on-personal-devices).
