### ISSUE TITLE
Request approval to update build configuration

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#326]
Hello @L-Crosby 

Please may I request approval to update the content build configuration? There are _no_ changes to published content.

This update:

- Standardises the location for storing image files during the build process.
- Standardises the syntax used for email links, for example when pointing people to the security@justice.gov.uk mailbox.

For reference, a full set of the configuration changes introduced by this update can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...images0331).

Many thanks.

**Comment by L-Crosby** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Build config update published.
