### ISSUE TITLE
Review request for updated password manager guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#327]
Hello @L-Crosby 

Following feedback and some questions, we've updated the guidance on password managers. In addition to now including KeePass (which is available as a standard installation option for some MoJ systems), we've also added a section so that any password manager available through an MoJ installation tool is approved for use.

Previews of the two updated sections may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/keepass0323/docs/password-managers.md#what-password-manager-to-use) and [here](https://github.com/ministryofjustice/security-guidance/blob/keepass0323/docs/general-user-video-and-messaging-apps-guidance.md#password-managers), respectively.

Please may I request a review of these proposed updates?

Many thanks.

**Comment by L-Crosby** [comment]
LGTM. Approved.

**Comment by warmanaMOJ** [comment]
Content published.
