### ISSUE TITLE
Request review of additional personalisation guidance.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#330]
Hello @L-Crosby 

Please may I request a review of a note added to the acceptable use guidance on personalisation?

Following a question in the discussion forums, an additional note has been added to the personalisation section regarding identification of government equipment. A preview of the proposed change may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/sticker0406/docs/acceptable-use.md#personalisation-of-equipment).

Many thanks.

**Comment by cybersquirrel** [comment]
This does feel a bit confusing for end-users - it's ok for the department to put a big sticker on my device saying "property of the MoJ", but for me to put one on is a breach of policy? That doesn't feel consistent for an end user.

**Comment by warmanaMOJ** [comment]
No problem - I'm happy to remove this one. It has been discussed, and a conclusion reached. 👍🏻
