### ISSUE TITLE
Request review of correction to security.txt link.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#332]
Hello @L-Crosby 

In the [Implementing security.txt](https://security-guidance.service.justice.gov.uk/implement-security-txt/#implementing-securitytxt) guidance, we currently require redirection to the old GitHub URL for the `security.txt` file. While not actually wrong or invalid, this link is not the best one to use.

This content update is to correct the security.txt link. Please may I request a review of the change? A preview of the modified guidance can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/securityTxt0406/docs/implement-security-txt.md).

The update also incorporates a simple build tooling refresh.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...securityTxt0406).

Many thanks.

**Comment by L-Crosby** [comment]
Approved. I have seen the conversation on the security slack channel that sets the context for this

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/implement-security-txt/).
