### ISSUE TITLE
Request review of new guidance on secure deletion of cloud materials

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#334]
Hello @L-Crosby 

Please may I request a review of new guidance on secure deletion of MoJ information stored on cloud technology?

A preview of the draft content may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/cloudDisposal1210/docs/secure-disposal-of-it-public-and-private-cloud.md).

This publication also adds cross references between related and relevant topics, as well as some minor fixes to broken links.

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...cloudDisposal1210).

Many thanks.

**Comment by L-Crosby** [comment]
LGTM. Very useful diagram. Approved.

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/secure-disposal-of-it-public-and-private-cloud/#secure-disposal-of-it---public-and-private-cloud).
