### ISSUE TITLE
Request review of update to build support packages.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#339]
Hello @L-Crosby or @cybersquirrel ,

Please may I request a review of updates to the build support packages? This is a simple update to apply security fixes to the build and content delivery packages. There are no changes to the policy or guidance content.

A full set of the changes introduced in this package may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...buildFix0414).

Many thanks.

**Comment by cybersquirrel** [comment]
LGTM!

**Comment by warmanaMOJ** [comment]
Build packages updated.
