### ISSUE TITLE
Request review of updates to overseas travel guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#350]
Hello @L-Crosby and @cybersquirrel 

We've had feedback from Group Security, requesting changes to emphasise correct advance notice and high-risk countries, and to add a warning about the 'maximum 10 years from issue' passport validity rule operated by some countries.

Previews of the two affected pages may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/overseas0515/docs/accessing-moj-it-systems-from-overseas.md#accessing-moj-it-systems-from-overseas) and [here](https://github.com/ministryofjustice/security-guidance/blob/overseas0515/docs/overseas-travel.md#overseas-travel).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...overseas0515).

Please may I invite your review comments?

Many thanks.

**Comment by cybersquirrel** [comment]
LGTM - thank you!

**Comment by warmanaMOJ** [comment]
Content published, thank you.
