### ISSUE TITLE
Request review of accessibility updates

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#357]
Hello @L-Crosby and @cybersquirrel 

Please may I request a review of updates being made to the content, for accessibility purposes?

Specifically, in response to feedback regarding use of a screen reader when reviewing policy documents, where we have made use of both `highlighting fonts` and also emphasis when someone **SHOULD** do something, we sought advice from the accessibility team.

Their guidance was that we could improve things, and therefore this publication introduces those improvements.

You can see an example of the changes in the Scope section of the draft [Acceptable Use Policy](https://github.com/ministryofjustice/security-guidance/blob/accessImprove0621/docs/acceptable-use-policy.md#scope). For comparison, the current publication can be seen [here](https://security-guidance.service.justice.gov.uk/acceptable-use-policy/#scope).

The changes are simple, but there are many of them, for the simple reason that the emphasis is used many times through the content. A full set of the proposed changes can be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...accessImprove0621).

Many thanks.

**Comment by cybersquirrel** [comment]
LGTM - very glad to see you taking this input from our accessibility colleagues.

**Comment by warmanaMOJ** [comment]
Thank you, updates [published](https://security-guidance.service.justice.gov.uk/changelog/#change-log-for-ministry-of-justice-moj-security-guidance).
