### ISSUE TITLE
Review of updates for non-MoJ email addresses

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#360]
Hello @cybersquirrel and @L-Crosby 

Please may I request a review of changes to align all contact email addresses through security@justice?

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...emailUpdate0701).

Many thanks.

**Comment by cybersquirrel** [comment]
LGTM - thank you.

**Comment by warmanaMOJ** [comment]
Closing following publication approval.
