### ISSUE TITLE
Request review of clarification re: use of personal devices to receive MFA codes

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#366]
Hello @cybersquirrel and @L-Crosby 

Please may I request a review of a clarification, stating that, if someone does not have an MoJ-issued mobile device, it is acceptable to use a personal device to receive an MFA code when logging in to an MoJ system? A preview of the extra clarification may be seen in the Note, [here](https://github.com/ministryofjustice/security-guidance/blob/personalDevice0513/docs/personal-devices.md#guidance).

Many thanks.

**Comment by cybersquirrel** [comment]
LGTM.

**Comment by warmanaMOJ** [comment]
Thank you, content [published}(https://security-guidance.service.justice.gov.uk/personal-devices/#guidance).
