### ISSUE TITLE
Request review of accuracy changes to Minimum User Clearance Requirements Guide

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#370]
Hello @cybersquirrel and @L-Crosby 

Please may I request a review of some minor updates to the Minimum User Clearance Requirements Guide? Specifically, a correction to the contact name of the Security Team, the reference to "Vetting Policy" should be corrected, and the embedded link in "Vetting Policy" should be to the GitHub page.

A preview of the modified section can be seen [here](https://github.com/ministryofjustice/security-guidance/blob/minimumClearance0722/docs/minimum-user-clearance-requirements-guide.md#minimum-user-clearance-requirements).

A full set of the changes introduced in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...minimumClearance0722).

Many thanks.

**Comment by cybersquirrel** [comment]
LGTM, thank you.

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/minimum-user-clearance-requirements-guide/#minimum-user-clearance-requirements).
