### ISSUE TITLE
Request review of minor update to Bluetooth guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#371]
Hello @cybersquirrel and @L-Crosby 

It was pointed out that some guidance in personal devices on _not_ connecting to vehicles using Bluetooth from MoJ devices ([here](https://security-guidance.service.justice.gov.uk/personal-devices/#connected-vehicles)) _also_ applies to the overall information on Bluetooth.

This update replicates the information across both topics. A preview of the additional paragraph may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/bluetooth0804/docs/bluetooth.md#connected-vehicles).

**Note:** This is not new or changed content; simply a re-use of existing approved material in a related topic.

Many thanks.

**Comment by cybersquirrel** [comment]
Thanks @warmanaMOJ . Happy with the reuse. Only thing was that on reading it through I noticed this sentence:

> The usual claim is only that the transferred data is deemed inaccessible to the platform menu.

which wasn't immediately clear to me. I think it's something like:
> Transferred information may no longer be immediately visible / accessible, but this is not the same as it being deleted from the vehicle.

?

**Comment by warmanaMOJ** [comment]
Thank you, good catch - that sentence is rather unclear. [Fixed](https://github.com/ministryofjustice/security-guidance/blob/bluetooth0804/docs/bluetooth.md#connected-vehicles) as per your suggestion, thank you.

**Comment by warmanaMOJ** [comment]
Thank you, [published](https://security-guidance.service.justice.gov.uk/bluetooth/#connected-vehicles).
