### ISSUE TITLE
Request review of new guidance on use of video conferencing hardware

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#373]
Hello @cybersquirrel and @L-Crosby 

In response to some questions and discussions about use of dedicated hardware for video and conference calls, we've draft an update to the video conferencing guidance.

A preview of the new section on hardware may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/videoConf0804/docs/general-user-video-and-messaging-apps-guidance.md#video-conference-hardware).

Please may I request a review of this new section?

Many thanks.

**Comment by cybersquirrel** [comment]
Happy with the additional text here, with two thoughts:
- For the future, but this specific page is starting to suffer scope creep and now covers quite a lot - from video hardware to approved apps. It might benefit from refactoring in the future.
- In the same vein, the paragraph introduces policy-esque statements (**bold** shalls / shall nots etc) in a guidance document. We should probably split out the policy aspects in the future.

**Comment by warmanaMOJ** [comment]
Agreed, thank you. I've added a task card to the backlog to tackle that eminently sensible refactoring.

**Comment by warmanaMOJ** [comment]
Content [published](https://security-guidance.service.justice.gov.uk/general-user-video-and-messaging-apps-guidance/#video-conference-hardware).
