### ISSUE TITLE
Request review of modification to remove poster download links

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#375]
Hello @cybersquirrel and @L-Crosby 

Please may I request a review of some minor changes to remove links for downloading some information posters? The information will be updated in due course with revised media.

Specifically, the proposed changes are:

- Current [passwords page](https://security-guidance.service.justice.gov.uk/passwords/) and preview of [revised version](https://github.com/ministryofjustice/security-guidance/blob/leaflets0808/docs/passwords.md).
- Current [ransomware page](https://security-guidance.service.justice.gov.uk/ransomware/) and preview of [revised version](https://github.com/ministryofjustice/security-guidance/blob/leaflets0808/docs/ransomware.md).
- Current [security culture page](https://security-guidance.service.justice.gov.uk/security-culture/) and preview of [revised version](https://github.com/ministryofjustice/security-guidance/blob/leaflets0808/docs/security-culture.md).

A full set of the changes proposed in this publication may be seen [here](https://github.com/ministryofjustice/security-guidance/compare/main...leaflets0808/).

Many thanks.

**Comment by cybersquirrel** [comment]
Approved, thank you.

**Comment by warmanaMOJ** [comment]
Content updated [published](https://security-guidance.service.justice.gov.uk/changelog/#change-log-for-ministry-of-justice-moj-security-guidance).
