### ISSUE TITLE
Update guidance to His Majesty's Government

### ISSUE THREAD

**Issue by cybersquirrel** [ministryofjustice/security-guidance#399]
There are a few references to Her Majesty's Government in the portfolio (expansions of HMG usually). These need to change to His Majesty's Government to reflect the new monarch.

**Comment by warmanaMOJ** [comment]
Hello @cybersquirrel and @L-Crosby 

I could only find one instance of 'Her', which I have corrected.

Please may I request a review of the change to update the content for **His** Majesty's Government. A preview of the updated section may be seen [here](https://github.com/ministryofjustice/security-guidance/blob/hmg1017/docs/reporting-personal-circumstance-changes.md#links-with-extremist-or-secretive-organisations).

Many thanks.

**Comment by warmanaMOJ** [comment]
Closing as content is no longer published.
