### ISSUE TITLE
Bug on Safari 13 (iOS)

### ISSUE THREAD

**Issue by andy-gg** [ministryofjustice/security-guidance#53]
On Safari 13, the last bullet point of each group is not clickable, including:
- Shared responsibility models
- Authorisation
- Vulnerability scanning
- Security Log Collection Maturity Tiers
- Web Check
- Using Lastpass enterprise
- Supplier Corporate IT
- Instruction & Confirmation letter
- Official, Official-Sensitive
- Reporting an incident

Note that the following links **do** work however:
- Cyber Security Consultancy Team: asking for help
- Vulnerability Disclosure Policy

**Comment by tomdMOJ** [comment]
Is this still an issue?

**Comment by andy-gg** [comment]
Correct - still a problem. Anyone with an iPhone with latest iOS should be able to replicate 👍🏻

**Comment by warmanaMOJ** [comment]
@andy-gg  Hello, I've just checked using Safari on an iPhone running 13.4.1. I can't immediately see a problem - if you get a moment, please would you confirm that the problem has 'gone away'? Many thanks!

**Comment by andy-gg** [comment]
good morning @warmanaMOJ - (to confirm), it is still an issue on 13.3.1 but I will perform an update to 13.4.1 shortly to see if it corrects it :)

**Comment by andy-gg** [comment]
@warmanaMOJ - update performed to 13.4.1 - issue still exists. (for example, "Share Responsibility Models" does not open a link unlike the option above which does ("Security Log Collection"))

**Comment by warmanaMOJ** [comment]
@andy-gg OK, thank you, yes, I see what you mean. It's interesting; the HTML appears to be well-formed, and all works fine on desktop, but not on iPhone (or indeed Chrome on Android, too). Very odd.

I'll see what i can do to fix this.

**Comment by warmanaMOJ** [comment]
@andy-gg  I've applied a simple fix. Not exactly elegant, but it seems to work. Would you give a try, please?

**Comment by andy-gg** [comment]
Yeah - it's a strange one. That's working for me now though... 

I wonder if instead of "<p> </p>", you could just put an &nbsp in instead so the formatting doesn't change? (no worries if you tried that though!) :) 

FYI - I'm also (perhaps unsurprisingly!) getting the same issue with the Technical Guidance too

**Comment by warmanaMOJ** [comment]
@andy-gg I'm glad the fix worked - and also, great minds think alike, the fix I tried first was to add `&nbsp;` like you suggested! Have a look at the changes in the index.md file.

I agree that the effect on formatting is not ideal - but it is still very usable, so I'll probably leave it as-is for the moment.

Anyway - many thanks for letting us know about the problem, thank you for your patience while we fixed it, and thank you for confirming it seems to be OK now.

**Comment by andy-gg** [comment]
No worries - thanks for sorting (and glad I didn't offend with my last comment - I posted without checking what you'd actually done to fix it, let alone tried before that). I kicked myself afterwards! 

Do you want me to raise the issue for Technical Guidance too?

**Comment by warmanaMOJ** [comment]
_<grin>_ No offence taken at all :-)

Yes, please, let 'em know over in technical guidance.

Thanks again.
