### ISSUE TITLE
Refine tools guidance to provide more detail about obligations, such as FOI.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#72]

**Comment by warmanaMOJ** [comment]
@cybersquirrel 

Draft update to tools guidance, including FOI and privacy information. Preview available [here](https://github.com/warmanaMOJ/security-guidance/blob/foi20200417/policies/general-user-video-and-messaging-apps-guidance.md).

Please would you check?

Thank you.

**Comment by cybersquirrel** [comment]
Looks good to me - thanks @warmana

**Comment by warmanaMOJ** [comment]
Thank you, content published ( #73  ).
