### ISSUE TITLE
Request approval to publish Malware guidance

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#93]
Hello @cybersquirrel ,

(FYI @tomdMOJ , @simonsMOJ )

Please may I request approval to publish the new Malware guidance, and an associated new landing page for security guidance?

- The new landing page can be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/Interim0710/index.md); it will replace the [current landing page](https://ministryofjustice.github.io/security-guidance/#moj-security--guidance).
- The Malware introduction page can be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/Interim0710/standards/malware-protection-guide-introduction.md).
- The Malware main content page 1 can be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/Interim0710/standards/malware-protection-guidance-defensive-layer-1.md).
- The Malware main content page 2 can be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/Interim0710/standards/malware-protection-guidance-defensive-layer-2.md).
- The Malware main content page 3 can be previewed [here](https://github.com/ministryofjustice/security-guidance/blob/Interim0710/standards/malware-protection-guidance-defensive-layer-3.md).

Please note that the nature of the documentation build system means that links to other content in the guidance, from _within_ these pages will not work. However, they have been tested on a local build; in the unlikely event of a link breaking, the fix should be quick and easy. Links to external sites, such as NCSC guidance, will work fine.

Many thanks.

**Comment by cybersquirrel** [comment]
Approved. I can think of a few changes we will likely want to make in future iterations, but let's not make perfect the enemy of progress. :) 

Thanks to all for their hard work on this.

**Comment by warmanaMOJ** [comment]
Thank you - published.
