### ISSUE TITLE
Request approval to publish updated guidance on "Lost Laptop or other IT security incident"

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/security-guidance#97]
@cybersquirrel Please may I request approval to publish this updated guidance on [Lost Laptop or other IT security incident](https://github.com/ministryofjustice/security-guidance/blob/Migrate0819/docs/lost-laptophardware.md).

It was originally published on the Intranet [here](https://intranet.justice.gov.uk/guidance/security/it-computer-security/lost-laptophardware/), and has been updated following feedback from OST.

Thank you.

**Comment by cybersquirrel** [comment]
Why would HMCTS & HMPPS users do different things to these sensible instructions? For Dom1 / Quantum devices we'd need them to report the loss in the same way to get the message to the service desk.

**Comment by warmanaMOJ** [comment]
@cybersquirrel Thank you, I've updated the draft accordingly. Same link as before.

**Comment by cybersquirrel** [comment]
Perfect -thank you @warmanaMOJ ! Approved.

**Comment by warmanaMOJ** [comment]
Thank you very much.
